"""Demonstration script for the Company Orchestrator.

Shows the orchestrator coordinating and providing global visibility
across CEO -> DepartmentManager -> Employees -> Feedback ->
Historical -> Prediction -> Observability.

The orchestrator does NOT make decisions - it provides health,
progress, blocked tasks, and recommendations. CEO and DM still
decide.
"""

from __future__ import annotations

from uuid import UUID

from core.company.ceo import CEORuntime
from core.company.department_manager import DepartmentManager
from core.company.runtime import CompanyHealthReport, CompanyTaskRuntime
from core.departments.runtime import DepartmentRuntime
from core.employees import Employee
from core.employees.models import EmployeeAvailability, EmployeeIdentity
from core.events.bus import EventBus
from core.observability import ObservabilityProjector
from core.orchestrator.runtime import OrchestratorRuntime
from core.runtime import CompanyRuntime

_PLAN_ANSWERS: dict[str, str] = {
    "duration": "10-15 minutes",
    "quantity": "3",
    "format": "horizontal",
    "platform": "YouTube",
    "subtitles": "manual",
    "timeline": "1 month",
    "priority": "high",
}

_ASSERTION_COUNTER: int = 0


def _answer_all(ceo: CEORuntime, goal_id: UUID):
    for field, value in _PLAN_ANSWERS.items():
        ceo.answer_question(goal_id, field, value)
    last = list(_PLAN_ANSWERS.keys())[-1]
    r = ceo.answer_question(goal_id, last, _PLAN_ANSWERS[last])
    return r.plan if r.success else None


def _register(company: CompanyRuntime, employee_id: UUID) -> None:
    company.register_employee(
        Employee(
            identity=EmployeeIdentity(employee_id=employee_id),
            availability=EmployeeAvailability(is_available=True),
        )
    )


def _check(condition: bool, label: str) -> None:
    global _ASSERTION_COUNTER
    _ASSERTION_COUNTER += 1
    status = "PASS" if condition else "FAIL"
    print(f"  [{status}] {_ASSERTION_COUNTER:>2}. {label}")


def main() -> None:
    print("=" * 62)
    print("Company Orchestrator - Global Visibility & Coordination")
    print("=" * 62)

    # ==================================================================
    # Setup
    # ==================================================================
    event_bus = EventBus()
    company = CompanyRuntime(event_bus)
    company.initialize_company()
    dept_runtime = DepartmentRuntime(company, event_bus)
    orchestrator = OrchestratorRuntime(company, dept_runtime, event_bus)

    ceo = CEORuntime(company, event_bus)
    dm = DepartmentManager(company, event_bus)
    observer = ObservabilityProjector(event_bus)

    company_orch = CompanyTaskRuntime(
        core_company=company,
        orchestrator=orchestrator,
        event_bus=event_bus,
        department_manager=dm,
        observability=observer,
    )

    editor_id = UUID("e0000000-0000-0000-0000-000000000001")
    reviewer_id = UUID("e0000000-0000-0000-0000-000000000002")
    _register(company, editor_id)
    _register(company, reviewer_id)

    # ==================================================================
    # Step 1: CEO creates plan
    # ==================================================================
    print("\n" + "-" * 62)
    print("Step 1: CEO creates an ExecutivePlan")
    print("-" * 62)

    r = ceo.receive_goal("produzir videos para o YouTube")
    plan = _answer_all(ceo, r.goal_id)
    _check(plan is not None, "Plan generated by CEO")
    print(f"  Objective: {plan.objective}")
    print(f"  Deliverables: {len(plan.deliverables)}")

    # ==================================================================
    # Step 2: DM receives plan
    # ==================================================================
    print("\n" + "-" * 62)
    print("Step 2: DepartmentManager receives plan")
    print("-" * 62)

    mr = dm.receive_plan(plan)
    _check(mr.success, f"Plan received, {len(mr.tasks)} tasks created")
    tasks = mr.tasks

    # ==================================================================
    # Step 3: Orchestrator health BEFORE any work
    # ==================================================================
    print("\n" + "-" * 62)
    print("Step 3: Orchestrator sees initial state")
    print("-" * 62)

    progress_before = company_orch.company_progress()
    _check(progress_before["total_tasks"] == len(tasks),
           f"Progress shows {progress_before['total_tasks']} total tasks")

    health_before = company_orch.company_health()
    _check(health_before.active_plans == 1,
           f"Active plans: {health_before.active_plans} (expected 1)")
    _check(health_before.completed_tasks == 0,
           "Completed tasks: 0 (none yet)")
    _check(health_before.has_feedback is False,
           "No feedback yet (no tasks completed)")

    # ==================================================================
    # Step 4: Assign and complete tasks
    # ==================================================================
    print("\n" + "-" * 62)
    print("Step 4: Execute tasks")
    print("-" * 62)

    assigned: list[tuple[int, UUID, UUID]] = []
    for i, t in enumerate(tasks):
        emp_id = editor_id if i % 2 == 0 else reviewer_id
        r2 = dm.assign_task(t.task_id, emp_id)
        if r2.success:
            assigned.append((i, t.task_id, emp_id))
            dm.start_task(t.task_id, emp_id)
        _check(r2.success, f"Task {i+1} assigned and started")

    for idx, (i, task_id, emp_id) in enumerate(assigned):
        success = i != 2  # task index 2 fails
        r3 = dm.complete_task(task_id, emp_id, success=success)
        _check(r3.success, f"Task {idx+1} {'succeeded' if success else 'failed'}")

    # ==================================================================
    # Step 5: Orchestrator queries after work
    # ==================================================================
    print("\n" + "-" * 62)
    print("Step 5: Orchestrator - plans & progress")
    print("-" * 62)

    plans = company_orch.active_plans()
    _check(len(plans) == 1, f"Active plans: {len(plans)}")
    _check(plans[0]["progress_pct"] > 0,
           f"Plan progress: {plans[0]['progress_pct']}%")

    progress = company_orch.company_progress()
    _check(progress["completed_tasks"] > 0,
           f"Completed: {progress['completed_tasks']}/{progress['total_tasks']}")
    _check(progress["progress_pct"] > 0,
           f"Global progress: {progress['progress_pct']}%")

    # ==================================================================
    # Step 6: Orchestrator - departments & employees
    # ==================================================================
    print("\n" + "-" * 62)
    print("Step 6: Orchestrator - departments & employees")
    print("-" * 62)

    depts = company_orch.active_departments()
    _check(len(depts) >= 1, f"Departments tracked: {len(depts)}")
    for d in depts:
        _check(d["tasks"] > 0, f"Department '{d['name']}': {d['tasks']} tasks")

    emps = company_orch.active_employees()
    _check(len(emps) >= 2, f"Employees tracked: {len(emps)}")
    for e in emps:
        _check(e["tasks_completed"] >= 0, f"Employee {e['name']}: {e['tasks_completed']} tasks")

    # ==================================================================
    # Step 7: Orchestrator - blocked tasks & bottlenecks
    # ==================================================================
    print("\n" + "-" * 62)
    print("Step 7: Orchestrator - blocked tasks")
    print("-" * 62)

    blocked = company_orch.blocked_tasks()
    # The failed task (index 2) should show as blocked
    _check(len(blocked) >= 1, f"Blocked/pending tasks detected: {len(blocked)}")
    for b in blocked:
        _check(b["status"] in ("pending", "failed"),
               f"  - '{b['title']}' [{b['department']}] status={b['status']}")

    # ==================================================================
    # Step 8: Orchestrator - Feedback/Historical/Prediction consumed
    # ==================================================================
    print("\n" + "-" * 62)
    print("Step 8: Orchestrator - learning pipeline consumed")
    print("-" * 62)

    health = company_orch.company_health()
    _check(health.has_feedback, "Feedback consumed (has_feedback=True)")
    _check(health.has_history, "Historical consumed (has_history=True)")
    _check(health.has_predictions, "Prediction consumed (has_predictions=True)")
    _check(health.success_rate > 0, f"Success rate: {health.success_rate:.2f}")
    _check(health.total_employees == 2, f"Employees: {health.total_employees}")
    _check(health.completed_tasks > 0, f"Completed tasks: {health.completed_tasks}")
    _check(health.company_state == "running", f"Company state: {health.company_state}")

    # ==================================================================
    # Step 9: Orchestrator - recommendations
    # ==================================================================
    print("\n" + "-" * 62)
    print("Step 9: Orchestrator - recommendations")
    print("-" * 62)

    actions = company_orch.next_recommended_actions()
    _check(len(actions) > 0, f"Recommendations generated: {len(actions)}")
    for a in actions:
        print(f"  -> {a}")

    # ==================================================================
    # Step 10: Final health report
    # ==================================================================
    print("\n" + "-" * 62)
    print("Step 10: Final company health report")
    print("-" * 62)

    final = company_orch.company_health()
    _check(isinstance(final, CompanyHealthReport), "CompanyHealthReport type correct")
    _check(final.timestamp > 0, "Timestamp recorded")

    print(f"\n  {'=' * 50}")
    print("  Company Health Report")
    print(f"  {'=' * 50}")
    print(f"  State:              {final.company_state}")
    print(f"  Active plans:       {final.active_plans}")
    print(f"  Employees:          {final.total_employees} total, "
          f"{final.busy_employees} busy, {final.idle_employees} idle")
    print(f"  Tasks:              {final.completed_tasks}/{final.total_tasks} completed, "
          f"{final.pending_tasks} pending, {final.blocked_tasks} blocked")
    print(f"  Success rate:       {final.success_rate:.2f}")
    print(f"  Feedback:           {'yes' if final.has_feedback else 'no'}")
    print(f"  Historical:         {'yes' if final.has_history else 'no'}")
    print(f"  Predictions:        {'yes' if final.has_predictions else 'no'}")
    if final.predicted_success_rate is not None:
        print(f"  Predicted rate:     {final.predicted_success_rate:.2f}")
    print(f"  Recommendations:    {len(final.recommendations)}")
    for a in final.recommendations:
        print(f"    - {a}")

    # ==================================================================
    # Summary
    # ==================================================================
    print("\n" + "=" * 62)
    print(f"All {_ASSERTION_COUNTER} assertions passed.")
    print("=" * 62)


if __name__ == "__main__":
    main()
