"""Telegram Bot API adapter — mock + real execution modes."""

from __future__ import annotations

import re
from typing import Any

from core.tools.adapters.base import AbstractToolAdapter
from core.tools.adapters.models import (
    AdapterExecutionResult,
    CredentialRequirement,
    ExecutionMode,
    OwnerGuidance,
    ToolRequest,
)
from core.tools.capabilities import Capability
from core.tools.http.errors import HttpError
from core.tools.provider_control import ProviderBudgetDecision, ProviderBudgetGuard
from core.tools.secrets.models import SecretKey


_TELEGRAM_TOKEN_RE = re.compile(r"^\d{6,12}:[A-Za-z0-9_-]{30,}$")
_MAX_TELEGRAM_TEXT = 4096


class TelegramAdapter(AbstractToolAdapter):
    """Adapter for Telegram Bot API publishing.

    MOCK mode returns deterministic responses.
    REAL mode calls Telegram Bot API through HttpClient + Provider.
    """

    def __init__(self) -> None:
        super().__init__()
        self._budget_guard: ProviderBudgetGuard | None = None

    @property
    def adapter_id(self) -> str:
        return "telegram_bot"

    @property
    def tool_name(self) -> str:
        return "Telegram Bot"

    def supported_capabilities(self) -> frozenset[Capability]:
        return frozenset({
            Capability.SOCIAL_MEDIA,
            Capability.TEXT_GENERATION,
        })

    def required_config_keys(self) -> tuple[str, ...]:
        return ("bot_token",)

    def required_credential_keys(self) -> tuple[str, ...]:
        return ("bot_token",)

    def credential_requirements(self) -> tuple[CredentialRequirement, ...]:
        return (CredentialRequirement(
            key="bot_token",
            label="Telegram Bot Token",
            description="Token generated by BotFather after creating the bot",
        ),)

    def validate_configuration(self, config: dict[str, Any]) -> bool:
        token = str(config.get("bot_token", ""))
        return (
            bool(token)
            and (
                _TELEGRAM_TOKEN_RE.match(token) is not None
                or token.startswith("test_telegram_token_")
                or token == "configured_via_secret_provider"
            )
        )

    def validate_credentials(self) -> bool:
        token = self._resolve_credential("bot_token")
        return bool(token) and (
            _TELEGRAM_TOKEN_RE.match(token) is not None
            or token.startswith("test_telegram_token_")
            or token == "configured_via_secret_provider"
        )

    def check_availability(self) -> bool:
        return True

    def owner_guidance(self) -> OwnerGuidance:
        return OwnerGuidance(
            steps=(
                "1. Abra o Telegram e converse com @BotFather",
                "2. Use /newbot, escolha nome e username do bot",
                "3. Copie o token mostrado pelo BotFather",
                "4. Guarde o token em segredo; ele permite controlar o bot",
                "5. Adicione o bot ao canal/grupo de destino e obtenha o chat_id",
            ),
            docs_url="https://core.telegram.org/bots/api",
            notes=(
                "Envio REAL exige bot_token, chat_id explicito, approved=True "
                "e limites de uso configurados quando ProviderBudgetGuard estiver ativo."
            ),
        )

    def set_budget_guard(self, budget_guard: ProviderBudgetGuard | None) -> None:
        """Inject a REAL-mode provider budget guard."""
        self._budget_guard = budget_guard

    # ------------------------------------------------------------------
    # Execution
    # ------------------------------------------------------------------

    def execute(self, request: ToolRequest) -> AdapterExecutionResult:
        if self._execution_mode == ExecutionMode.REAL:
            return self._execute_real(request)
        return self._execute_mock(request)

    def _execute_mock(self, request: ToolRequest) -> AdapterExecutionResult:
        action = str(request.params.get("action", "get_me"))
        if action == "send_message":
            validation = self._validate_send_params(request, require_chat=True)
            if validation:
                return validation
            approved = bool(request.params.get("approved", False))
            if not approved:
                return AdapterExecutionResult(
                    success=False,
                    summary="Telegram message blocked before publish: approval required.",
                    output={
                        "status": "approval_required",
                        "channel": "telegram",
                        "_mock": True,
                    },
                    error="Telegram send_message requires approved=True.",
                )
            text = str(request.params.get("text", ""))
            chat_id = str(request.params.get("chat_id", ""))
            return AdapterExecutionResult(
                success=True,
                summary=f"Telegram message prepared for chat {chat_id}",
                output={
                    "status": "sent_mock",
                    "message_id": 1001,
                    "chat_id": chat_id,
                    "text_length": len(text),
                    "channel": "telegram",
                    "_mock": True,
                },
            )
        return AdapterExecutionResult(
            success=True,
            summary="Telegram bot metadata retrieved",
            output={
                "bot_id": 123456789,
                "username": "ai_content_factory_bot",
                "first_name": "AI Content Factory",
                "can_join_groups": True,
                "can_read_all_group_messages": False,
                "_mock": True,
            },
        )

    def _execute_real(self, request: ToolRequest) -> AdapterExecutionResult:
        action = str(request.params.get("action", "get_me"))
        client = self._http_client
        provider = self._provider
        if client is None or provider is None:
            return AdapterExecutionResult(
                success=False,
                summary="",
                error="Telegram REAL mode requires HttpClient and Provider",
            )

        token = self._resolve_credential("bot_token")
        if not token:
            return AdapterExecutionResult(
                success=False,
                summary="",
                error="Telegram REAL mode requires 'bot_token' credential",
            )

        if action == "send_message":
            return self._send_message_real(request, token)
        return self._get_me_real(token)

    def _get_me_real(self, token: str) -> AdapterExecutionResult:
        budget_decision = self._budget_check("get_me", 1, "requests")
        if budget_decision is not None and not budget_decision.allowed:
            return self._budget_blocked_result("get_me", budget_decision)

        client = self._require_client()
        url = self._endpoint(token, "getMe")
        try:
            resp = client.get(url)
        except HttpError as exc:
            self._budget_record("get_me", 1, "requests", success=False, billable=False)
            return AdapterExecutionResult(
                success=False,
                summary="Telegram bot validation failed before response.",
                output={
                    "_real": True,
                    "_http_error": type(exc).__name__,
                },
                error=type(exc).__name__,
            )

        body = resp.body if isinstance(resp.body, dict) else {}
        ok = resp.status_code == 200 and bool(body.get("ok", False))
        result = body.get("result", {}) if isinstance(body.get("result", {}), dict) else {}
        self._budget_record("get_me", 1, "requests", success=ok, billable=False)
        return AdapterExecutionResult(
            success=ok,
            summary=(
                f"Telegram bot validated: @{result.get('username', '')}"
                if ok else f"Telegram getMe failed: HTTP {resp.status_code}"
            ),
            output={
                "bot_id": result.get("id", 0),
                "username": result.get("username", ""),
                "first_name": result.get("first_name", ""),
                "can_join_groups": result.get("can_join_groups", False),
                "can_read_all_group_messages": result.get("can_read_all_group_messages", False),
                "_real": True,
            },
            error="" if ok else self._safe_telegram_error(body, resp.status_code),
        )

    def _send_message_real(self, request: ToolRequest, token: str) -> AdapterExecutionResult:
        validation = self._validate_send_params(request, require_chat=True)
        if validation:
            return validation
        if not bool(request.params.get("approved", False)):
            return AdapterExecutionResult(
                success=False,
                summary="Telegram REAL message blocked before publish: approval required.",
                output={
                    "status": "approval_required",
                    "channel": "telegram",
                    "_real": True,
                    "_blocked_by_approval": True,
                },
                error="Telegram send_message requires approved=True before REAL publish.",
            )

        text = str(request.params.get("text", ""))
        chat_id = str(request.params.get("chat_id", ""))
        body: dict[str, Any] = {
            "chat_id": chat_id,
            "text": text,
        }
        optional_fields = (
            "parse_mode",
            "disable_notification",
            "protect_content",
            "message_thread_id",
            "reply_to_message_id",
        )
        for field in optional_fields:
            if field in request.params:
                body[field] = request.params[field]
        if bool(request.params.get("disable_web_page_preview", True)):
            body["link_preview_options"] = {"is_disabled": True}

        budget_decision = self._budget_check("send_message", 1, "messages")
        if budget_decision is not None and not budget_decision.allowed:
            return self._budget_blocked_result("send_message", budget_decision)

        client = self._require_client()
        url = self._endpoint(token, "sendMessage")
        headers = {"Content-Type": "application/json"}
        try:
            resp = client.post(url, headers=headers, body=body)
        except HttpError as exc:
            self._budget_record("send_message", 1, "messages", success=False, billable=False)
            return AdapterExecutionResult(
                success=False,
                summary="Telegram REAL send failed before response.",
                output={
                    "status": "failed",
                    "channel": "telegram",
                    "_real": True,
                    "_http_error": type(exc).__name__,
                },
                error=type(exc).__name__,
            )

        resp_body = resp.body if isinstance(resp.body, dict) else {}
        ok = resp.status_code == 200 and bool(resp_body.get("ok", False))
        result = resp_body.get("result", {}) if isinstance(resp_body.get("result", {}), dict) else {}
        message = result.get("message_id", 0)
        self._budget_record("send_message", 1, "messages", success=ok, billable=ok)
        return AdapterExecutionResult(
            success=ok,
            summary=(
                f"Telegram message sent: {message}"
                if ok else f"Telegram send failed: HTTP {resp.status_code}"
            ),
            output={
                "status": "sent" if ok else "failed",
                "message_id": message,
                "chat_id": chat_id,
                "text_length": len(text),
                "channel": "telegram",
                "_real": True,
            },
            error="" if ok else self._safe_telegram_error(resp_body, resp.status_code),
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _resolve_credential(self, key: str) -> str:
        if self._secret_provider is not None:
            for secret_key in (
                SecretKey(key=key, tool_id=self.adapter_id),
                SecretKey(key=key, provider="telegram"),
            ):
                secret = self._secret_provider.get(secret_key)
                if secret is not None:
                    return secret.value
        return str(self._config.get(key, ""))

    def _endpoint(self, token: str, method: str) -> str:
        provider = self._provider
        base = provider.base_url.rstrip("/") if provider is not None else "https://api.telegram.org"
        return f"{base}/bot{token}/{method}"

    def _validate_send_params(
        self,
        request: ToolRequest,
        *,
        require_chat: bool,
    ) -> AdapterExecutionResult | None:
        text = str(request.params.get("text", ""))
        if not text.strip():
            return AdapterExecutionResult(
                success=False,
                summary="",
                output={"channel": "telegram"},
                error="Telegram send_message requires non-empty text.",
            )
        if len(text) > _MAX_TELEGRAM_TEXT:
            return AdapterExecutionResult(
                success=False,
                summary="",
                output={
                    "channel": "telegram",
                    "text_length": len(text),
                    "max_text_length": _MAX_TELEGRAM_TEXT,
                },
                error="Telegram text exceeds 4096 characters.",
            )
        if require_chat and not str(request.params.get("chat_id", "")).strip():
            return AdapterExecutionResult(
                success=False,
                summary="",
                output={"channel": "telegram"},
                error="Telegram send_message requires chat_id.",
            )
        return None

    def _require_client(self) -> Any:
        if self._http_client is None:
            raise RuntimeError("TelegramAdapter requires HttpClient.")
        return self._http_client

    def _budget_check(
        self,
        operation: str,
        units: int,
        unit_name: str,
    ) -> ProviderBudgetDecision | None:
        if self._budget_guard is None:
            return None
        return self._budget_guard.check(
            provider="telegram",
            operation=operation,
            units=units,
            unit_name=unit_name,
        )

    def _budget_record(
        self,
        operation: str,
        units: int,
        unit_name: str,
        *,
        success: bool,
        billable: bool,
    ) -> None:
        if self._budget_guard is None:
            return
        self._budget_guard.record_usage(
            provider="telegram",
            operation=operation,
            mode=self._execution_mode.value,
            units=units,
            unit_name=unit_name,
            success=success,
            billable=billable,
            metadata={"adapter": self.adapter_id},
        )

    @staticmethod
    def _budget_blocked_result(
        operation: str,
        decision: ProviderBudgetDecision,
    ) -> AdapterExecutionResult:
        return AdapterExecutionResult(
            success=False,
            summary=f"Telegram REAL {operation} blocked by provider budget guard.",
            output={
                "_real": True,
                "_blocked_by_budget": True,
                "provider_control": decision.to_dict(),
            },
            error=decision.reason,
        )

    @staticmethod
    def _safe_telegram_error(body: dict[str, Any], status_code: int) -> str:
        description = str(body.get("description", "")).strip()
        if description:
            return description
        return f"HTTP {status_code}"
