/* Market Intelligence — Mock Data v1.0 */
/* Dados determinísticos para protótipo offline. */
const MockData = (function() {
  /* ========= SOURCES ========= */
  function buildSources() {
    return [
      {
        source_id: 'SRC-001',
        title: 'Como escalamos de R$ 0 a R$ 80k/mes em 6 meses',
        type: 'youtube_podcast',
        url: 'https://youtube.com/watch?v=mock001',
        format: 'video',
        language: 'pt-BR',
        speaker_count: 2,
        speakers: [{ role: 'entrevistador', name: 'Joao' }, { role: 'especialista', name: 'Carlos' }],
        duration_sec: 2760,
        domain_tags: ['marketing_digital', 'funil', 'coproducao'],
        date: '2026-06-15',
        status: 'transcript_available',
        credibility: 0.4,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-002',
        title: 'Como faturamos R$ 40k com um lançamento via CheckoutFlow',
        type: 'youtube_podcast',
        url: 'https://youtube.com/watch?v=mock002',
        format: 'video',
        language: 'pt-BR',
        speaker_count: 1,
        speakers: [{ role: 'especialista', name: 'Ana' }],
        duration_sec: 1920,
        domain_tags: ['checkout', 'lancamento', 'infoproduto'],
        date: '2026-06-20',
        status: 'transcript_available',
        credibility: 0.35,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-003',
        title: 'Nossa pilha de tecnologia para edição de vídeo em escala',
        type: 'blog_post',
        url: 'https://exemplo.com/blog/pilha-edicao-video',
        format: 'text',
        language: 'pt-BR',
        speaker_count: 1,
        speakers: [{ role: 'autor', name: 'Rafael' }],
        duration_sec: 0,
        domain_tags: ['video_edition', 'tecnologia', 'automacao'],
        date: '2026-06-10',
        status: 'transcript_available',
        credibility: 0.5,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-004',
        title: 'Painel sobre ecossistema de afiliados no Brasil em 2026',
        type: 'youtube_podcast',
        url: 'https://youtube.com/watch?v=mock004',
        format: 'video',
        language: 'pt-BR',
        speaker_count: 3,
        speakers: [{ role: 'moderador', name: 'Pedro' }, { role: 'afiliado', name: 'Lucas' }, { role: 'produtor', name: 'Marina' }],
        duration_sec: 3300,
        domain_tags: ['afiliados', 'ecossistema', 'comissao'],
        date: '2026-06-25',
        status: 'transcript_available',
        credibility: 0.45,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-005',
        title: 'Oportunidades com TikTok Shop no Brasil',
        type: 'youtube_podcast',
        url: 'https://youtube.com/watch?v=mock005',
        format: 'video',
        language: 'pt-BR',
        speaker_count: 2,
        speakers: [{ role: 'especialista', name: 'Juliana' }, { role: 'entrevistador', name: 'Rogério' }],
        duration_sec: 2100,
        domain_tags: ['tiktok_shop', 'social_commerce', 'oportunidade'],
        date: '2026-07-01',
        status: 'transcript_available',
        credibility: 0.3,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-006',
        title: 'Como usamos IA para criar 100 vídeos por dia',
        type: 'blog_post',
        url: 'https://exemplo.com/blog/ia-100-videos',
        format: 'text',
        language: 'pt-BR',
        speaker_count: 1,
        speakers: [{ role: 'autor', name: 'Tiago' }],
        duration_sec: 0,
        domain_tags: ['ia', 'automacao', 'video_em_escala'],
        date: '2026-05-20',
        status: 'transcript_available',
        credibility: 0.35,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-007',
        title: 'Estrategia de coprodução multi-canal de conteudo',
        type: 'youtube_podcast',
        url: 'https://youtube.com/watch?v=mock007',
        format: 'video',
        language: 'pt-BR',
        speaker_count: 3,
        speakers: [{ role: 'mentor', name: 'Fábio' }, { role: 'aluna', name: 'Cristina' }, { role: 'aluno', name: 'Marcelo' }],
        duration_sec: 3600,
        domain_tags: ['coproducao', 'conteudo', 'multi-canal'],
        date: '2026-06-28',
        status: 'transcript_available',
        credibility: 0.5,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-008',
        title: 'Ferramentas de checkout que testamos em 2026',
        type: 'blog_post',
        url: 'https://exemplo.com/blog/checkout-testados',
        format: 'text',
        language: 'pt-BR',
        speaker_count: 1,
        speakers: [{ role: 'autor', name: 'Daniela' }],
        duration_sec: 0,
        domain_tags: ['checkout', 'ferramentas', 'comparacao'],
        date: '2026-05-30',
        status: 'transcript_available',
        credibility: 0.5,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-009',
        title: 'Webinario sobre edição de vídeo para afiliados',
        type: 'webinar',
        url: 'https://exemplo.com/webinar/edicao-afiliados',
        format: 'video',
        language: 'pt-BR',
        speaker_count: 1,
        speakers: [{ role: 'palestrante', name: 'Felipe' }],
        duration_sec: 2700,
        domain_tags: ['video_edition', 'afiliados', 'producao'],
        date: '2026-06-05',
        status: 'transcript_available',
        credibility: 0.4,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-010',
        title: 'Como construímos uma agencia de conteúdo com IA',
        type: 'youtube_podcast',
        url: 'https://youtube.com/watch?v=mock010',
        format: 'video',
        language: 'pt-BR',
        speaker_count: 2,
        speakers: [{ role: 'entrevistador', name: 'Paulo' }, { role: 'especialista', name: 'Renata' }],
        duration_sec: 2400,
        domain_tags: ['agencia', 'conteudo', 'ia'],
        date: '2026-07-05',
        status: 'transcript_available',
        credibility: 0.4,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-011',
        title: 'Analise de ferramentas de trafego pago para afiliados',
        type: 'blog_post',
        url: 'https://exemplo.com/blog/trafego-afiliados',
        format: 'text',
        language: 'pt-BR',
        speaker_count: 1,
        speakers: [{ role: 'autor', name: 'Gustavo' }],
        duration_sec: 0,
        domain_tags: ['trafego', 'afiliados', 'midia_paga'],
        date: '2026-04-15',
        status: 'transcript_available',
        credibility: 0.45,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-012',
        title: 'Podcast sobre Ecossistema de Funis e Coprodução',
        type: 'youtube_podcast',
        url: 'https://youtube.com/watch?v=mock012',
        format: 'video',
        language: 'pt-BR',
        speaker_count: 2,
        speakers: [{ role: 'entrevistador', name: 'Leandro' }, { role: 'convidado', name: 'Eduardo' }],
        duration_sec: 4800,
        domain_tags: ['funis', 'coproducao', 'ecossistema'],
        date: '2026-07-10',
        status: 'transcript_needed',
        credibility: 0.6,
        transcript_path: '',
        collecting_context: 'Fonte especial — sem conteudo inventado. Transcricao pendente.'
      },
      {
        source_id: 'SRC-013',
        title: 'Case: Crescimento de R$ 0 a R$ 200k/mes com infoprodutos',
        type: 'youtube_podcast',
        url: 'https://youtube.com/watch?v=mock013',
        format: 'video',
        language: 'pt-BR',
        speaker_count: 1,
        speakers: [{ role: 'especialista', name: 'Roberto' }],
        duration_sec: 1560,
        domain_tags: ['infoproduto', 'crescimento', 'case'],
        date: '2026-07-08',
        status: 'transcript_available',
        credibility: 0.25,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-014',
        title: 'Ferramentas de CRM e gestao para afiliados',
        type: 'blog_post',
        url: 'https://exemplo.com/blog/crm-afiliados',
        format: 'text',
        language: 'pt-BR',
        speaker_count: 1,
        speakers: [{ role: 'autor', name: 'Sandra' }],
        duration_sec: 0,
        domain_tags: ['crm', 'gestao', 'afiliados'],
        date: '2026-06-12',
        status: 'transcript_available',
        credibility: 0.5,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-015',
        title: 'Estrategias de conteudo para TikTok em 2026',
        type: 'youtube_podcast',
        url: 'https://youtube.com/watch?v=mock015',
        format: 'video',
        language: 'pt-BR',
        speaker_count: 2,
        speakers: [{ role: 'especialista', name: 'Camila' }, { role: 'entrevistador', name: 'Thiago' }],
        duration_sec: 1800,
        domain_tags: ['social_short', 'conteudo', 'estrategia'],
        date: '2026-07-12',
        status: 'transcript_available',
        credibility: 0.4,
        transcript_path: '',
        collecting_context: ''
      },
      {
        source_id: 'SRC-016',
        title: 'Guia de ferramentas de analytics para funis de venda',
        type: 'blog_post',
        url: 'https://exemplo.com/blog/analytics-funis',
        format: 'text',
        language: 'pt-BR',
        speaker_count: 1,
        speakers: [{ role: 'autor', name: 'Eduardo' }],
        duration_sec: 0,
        domain_tags: ['analytics', 'funil', 'ferramentas'],
        date: '2026-05-25',
        status: 'transcript_available',
        credibility: 0.55,
        transcript_path: '',
        collecting_context: ''
      }
    ];
  }
  /* ========= SEGMENTS ========= */
  function buildSegments() {
    return [
      { segment_id: 'SEG-001-a', source_id: 'SRC-001', start_time: 42, speaker: 'Carlos', text: 'No comeco a gente nao tinha processo nenhum. Era tudo manual. A gente gravava, editava, publicava. Zero automacao.' },
      { segment_id: 'SEG-001-b', source_id: 'SRC-001', start_time: 180, speaker: 'Carlos', text: 'A gente comecou a usar o VideoSprint pra gerar shorts automaticamente. Isso foi um divisor de aguas.' },
      { segment_id: 'SEG-001-c', source_id: 'SRC-001', start_time: 340, speaker: 'Carlos', text: 'Em 3 meses a gente tava gerando 60 mil reais por mes. Parecia mentira mas era real.' },
      { segment_id: 'SEG-001-d', source_id: 'SRC-001', start_time: 520, speaker: 'Carlos', text: 'Depois a gente entrou na coproducao. Trouxe 3 parceiros, cada um cuidava de uma parte.' },
      { segment_id: 'SEG-001-e', source_id: 'SRC-001', start_time: 750, speaker: 'Carlos', text: 'O funil era simples: trafego organico no TikTok, lead magnet no Telegram, venda no CheckoutFlow. Gastava uns 2 mil por mes de trafego.' },
      { segment_id: 'SEG-001-f', source_id: 'SRC-001', start_time: 900, speaker: 'Joao', text: 'Mas isso e replicavel? Tipo, qualquer pessoa pode fazer isso?' },
      { segment_id: 'SEG-001-g', source_id: 'SRC-001', start_time: 920, speaker: 'Carlos', text: 'Olha, o processo em si e replicavel, mas exige disciplina. Nao e magica, e execucao.' },
      { segment_id: 'SEG-001-h', source_id: 'SRC-001', start_time: 1120, speaker: 'Carlos', text: 'A gente testou 5 ferramentas de edicao. ClipForge pra mobile, Premiere pra desktop, e DaVinci quando precisava de qualidade.' },
      { segment_id: 'SEG-001-i', source_id: 'SRC-001', start_time: 1400, speaker: 'Carlos', text: 'O custo de aquisicao por lead era uns R$ 3,50. No comeco era R$ 8,00. A otimizacao veio com o tempo.' },
      { segment_id: 'SEG-001-j', source_id: 'SRC-001', start_time: 1800, speaker: 'Joao', text: 'Qual era a margem liquida?' },
      { segment_id: 'SEG-001-k', source_id: 'SRC-001', start_time: 1820, speaker: 'Carlos', text: 'Margem liquida girava em torno de 35 a 40 por cento. Mas isso variava muito de mes.' },
      { segment_id: 'SEG-001-l', source_id: 'SRC-001', start_time: 2100, speaker: 'Carlos', text: 'Estrategia de conteudo: 3 videos longos por semana, 15 shorts por dia. Shorts no TikTok e Reels, longos no YouTube.' },
      { segment_id: 'SEG-001-m', source_id: 'SRC-001', start_time: 2400, speaker: 'Carlos', text: 'A gente perdeu uns 6 mil reais num produto que nao vingou. Acontece. Faz parte do jogo.' },
      { segment_id: 'SEG-001-n', source_id: 'SRC-001', start_time: 2600, speaker: 'Carlos', text: 'link na descricao do video, galera' },
      { segment_id: 'SEG-002-a', source_id: 'SRC-002', start_time: 30, speaker: 'Ana', text: 'Foi um lancamento de 7 dias. A gente usou CheckoutFlow como plataforma de checkout.' },
      { segment_id: 'SEG-002-b', source_id: 'SRC-002', start_time: 200, speaker: 'Ana', text: 'Faturamento bruto foi 40 mil reais. Custo total uns 12 mil. Lucro liquido 28 mil.' },
      { segment_id: 'SEG-002-c', source_id: 'SRC-002', start_time: 400, speaker: 'Ana', text: 'A maior parte do trafego veio de anuncios no Facebook. Gastei uns 8 mil em anuncios.' },
      { segment_id: 'SEG-002-d', source_id: 'SRC-002', start_time: 600, speaker: 'Ana', text: 'Usei ChatFlow pra fazer o sequenciamento de mensagens no Mensagens.' },
      { segment_id: 'SEG-002-e', source_id: 'SRC-002', start_time: 800, speaker: 'Ana', text: 'Teve 120 vendas no total. Ticket medio de R$ 333.' },
      { segment_id: 'SEG-002-f', source_id: 'SRC-002', start_time: 1000, speaker: 'Ana', text: 'O produto era um curso de edicao de video pra iniciantes.' },
      { segment_id: 'SEG-002-g', source_id: 'SRC-002', start_time: 1200, speaker: 'Ana', text: 'A taxa de conversao de lead pra venda foi 3.2 por cento.' },
      { segment_id: 'SEG-002-h', source_id: 'SRC-002', start_time: 1400, speaker: 'Ana', text: 'Um terco das vendas veio de afiliados. Dois tercos de trafego direto.' },
      { segment_id: 'SEG-002-i', source_id: 'SRC-002', start_time: 1600, speaker: 'Ana', text: 'Nao, nao tenho print de tudo isso. Mas os dados tao no CheckoutFlow.' },
      { segment_id: 'SEG-002-j', source_id: 'SRC-002', start_time: 1800, speaker: 'Ana', text: 'Se quiser comecar tambeem, entra pro meu curso que tem o passo a passo' },
      { segment_id: 'SEG-003-a', source_id: 'SRC-003', start_time: 0, speaker: 'autor', text: 'Nossa pilha de edicao de video: RenderWave para render final, ClipForge para shorts rapidos, e FFmpeg para automacao de batch.' },
      { segment_id: 'SEG-003-b', source_id: 'SRC-003', start_time: 0, speaker: 'autor', text: 'Usamos ReviewLoop para review com clientes. Integra direto com DaVinci.' },
      { segment_id: 'SEG-003-c', source_id: 'SRC-003', start_time: 0, speaker: 'autor', text: 'Geramos 200 videos por mes com uma equipe de 3 editores. Antes era 40 videos com 5 pessoas.' },
      { segment_id: 'SEG-004-a', source_id: 'SRC-004', start_time: 120, speaker: 'Lucas', text: 'Como afiliado, minha taxa media de comissao e 50 por cento em infoprodutos.' },
      { segment_id: 'SEG-004-b', source_id: 'SRC-004', start_time: 300, speaker: 'Lucas', text: 'Ja cheguei a faturar R$ 30k num mes so de comissao. Mas foi um mes excepcional.' },
      { segment_id: 'SEG-004-c', source_id: 'SRC-004', start_time: 500, speaker: 'Marina', text: 'Como produtora, pago 60 por cento de comissao pros melhores afiliados. Eles geram 70 por cento das minhas vendas.' },
      { segment_id: 'SEG-004-d', source_id: 'SRC-004', start_time: 700, speaker: 'Pedro', text: 'O ecossistema de afiliados no Brasil movimentou bilhoes em 2025. A tendencia e crescer mais.' },
      { segment_id: 'SEG-004-e', source_id: 'SRC-004', start_time: 900, speaker: 'Lucas', text: 'Ferramentas que uso: CheckoutFlow como plataforma, MailCraft pra email, e FormCraft pra captura.' },
      { segment_id: 'SEG-004-f', source_id: 'SRC-004', start_time: 1200, speaker: 'Lucas', text: 'Invisto cerca de R$ 5 mil por mes em trafego pago. ROI medio de 3x.' },
      { segment_id: 'SEG-004-g', source_id: 'SRC-004', start_time: 1500, speaker: 'Marina', text: 'O problema maior hoje nao e producao de conteudo, e distribuicao. Tem muito conteudo, pouco alcance.' },
      { segment_id: 'SEG-004-h', source_id: 'SRC-004', start_time: 1800, speaker: 'Lucas', text: 'Concordo. Eu posto 20 conteudos por dia e so 2 ou 3 bombam.' },
      { segment_id: 'SEG-004-i', source_id: 'SRC-004', start_time: 2100, speaker: 'Lucas', text: 'Uso o VideoSprint, o DesignNest, e o GenText pra ajudar no processo criativo.' },
      { segment_id: 'SEG-004-j', source_id: 'SRC-004', start_time: 2500, speaker: 'Marina', text: 'Nao confio em IA pra criar conteudo do zero. Uso so pra revisao e organizacao.' },
      { segment_id: 'SEG-005-a', source_id: 'SRC-005', start_time: 60, speaker: 'Juliana', text: 'O TikTok Shop ainda ta engatinhando no Brasil, mas o potencial e gigantesco.' },
      { segment_id: 'SEG-005-b', source_id: 'SRC-005', start_time: 300, speaker: 'Juliana', text: 'Nos Estados Unidos o TikTok Shop ja fez 20 bilhoes em vendas. Aqui deve explodir em 2027.' },
      { segment_id: 'SEG-005-c', source_id: 'SRC-005', start_time: 600, speaker: 'Juliana', text: 'A vantagem do TikTok Shop e que a venda acontece dentro do proprio app. Zero atrito.' },
      { segment_id: 'SEG-005-d', source_id: 'SRC-005', start_time: 900, speaker: 'Juliana', text: 'Mas nao e qualquer produto que funciona. Produto visual, que da pra mostrar em 15 segundos.' },
      { segment_id: 'SEG-005-e', source_id: 'SRC-005', start_time: 1200, speaker: 'Juliana', text: 'Eu testei com alguns produtos e tive resultados mistos. Nada conclusivo ainda.' },
      { segment_id: 'SEG-006-a', source_id: 'SRC-006', start_time: 0, speaker: 'autor', text: 'Criamos um pipeline que usa SmartModel pra gerar scripts, VoiceForge pra narracao, e FFmpeg pra render.' },
      { segment_id: 'SEG-006-b', source_id: 'SRC-006', start_time: 0, speaker: 'autor', text: 'Conseguimos escalar pra 100 videos por dia com 1 operador. O custo por video caiu pra R$ 0,50.' },
      { segment_id: 'SEG-006-c', source_id: 'SRC-006', start_time: 0, speaker: 'autor', text: 'Usamos templates no MotionCraft com datasource JSON pra gerar variacoes.' },
      { segment_id: 'SEG-007-a', source_id: 'SRC-007', start_time: 100, speaker: 'Fabio', text: 'Coproducao e o modelo mais sustentavel que ja vi. Cada parceiro faz o que sabe.' },
      { segment_id: 'SEG-007-b', source_id: 'SRC-007', start_time: 400, speaker: 'Fabio', text: 'Um faz video, outro faz design, outro faz trafego. Divide o lucro proporcional.' },
      { segment_id: 'SEG-007-c', source_id: 'SRC-007', start_time: 700, speaker: 'Cristina', text: 'Eu entrei na coproducao sem saber nada. Aprendi fazendo. Em 4 meses tava ganhando 10 mil.' },
      { segment_id: 'SEG-007-d', source_id: 'SRC-007', start_time: 1100, speaker: 'Marcelo', text: 'O desafio e a coordenacao. Sem um processo claro, vira bagunca.' },
      { segment_id: 'SEG-007-e', source_id: 'SRC-007', start_time: 1500, speaker: 'Fabio', text: 'Usamos TaskHub pra gestao, TeamChat pra comunicacao, e FileVault pros arquivos.' },
      { segment_id: 'SEG-007-f', source_id: 'SRC-007', start_time: 2000, speaker: 'Cristina', text: 'Produzo 5 videos por semana. Cada video demora umas 4 horas, da ideia ao publicado.' },
      { segment_id: 'SEG-007-g', source_id: 'SRC-007', start_time: 2600, speaker: 'Marcelo', text: 'Minha taxa de conversao de lead pra venda e 4.5 por cento. Considero boa pro nicho.' },
      { segment_id: 'SEG-008-a', source_id: 'SRC-008', start_time: 0, speaker: 'autor', text: 'Testei 6 plataformas de checkout: CheckoutFlow, SellEngine, FlexCheckout, ConvertNow, Payt e LowFeePay.' },
      { segment_id: 'SEG-008-b', source_id: 'SRC-008', start_time: 0, speaker: 'autor', text: 'CheckoutFlow tem a maior base de afiliados. ConvertNow tem a melhor taxa de conversao. FlexCheckout e a mais flexivel.' },
      { segment_id: 'SEG-008-c', source_id: 'SRC-008', start_time: 0, speaker: 'autor', text: 'LowFeePay cobra 5.9 por cento por venda. CheckoutFlow cobra 9.9 por cento mais taxa fixa. A diferença e grande.' },
      { segment_id: 'SEG-008-d', source_id: 'SRC-008', start_time: 0, speaker: 'autor', text: 'Nenhuma plataforma oferece tudo. A escolha depende do seu produto e publico.' },
      { segment_id: 'SEG-009-a', source_id: 'SRC-009', start_time: 60, speaker: 'Felipe', text: 'Edicao de video pra afiliado tem que ser rapida. Ninguem tem tempo de passar horas editando.' },
      { segment_id: 'SEG-009-b', source_id: 'SRC-009', start_time: 300, speaker: 'Felipe', text: 'Uso ClipForge pra 90 por cento dos meus videos. E rapido, free e tem tudo que precisa.' },
      { segment_id: 'SEG-009-c', source_id: 'SRC-009', start_time: 600, speaker: 'Felipe', text: 'Template e a chave. Cria um template uma vez e usa pra sempre.' },
      { segment_id: 'SEG-009-d', source_id: 'SRC-009', start_time: 900, speaker: 'Felipe', text: 'Faco 15 videos por hora com template. Antes era 1 video por hora.' },
      { segment_id: 'SEG-010-a', source_id: 'SRC-010', start_time: 60, speaker: 'Renata', text: 'A gente construiu uma agencia de conteudo que entrega 500 pecas por mes pra 10 clientes.' },
      { segment_id: 'SEG-010-b', source_id: 'SRC-010', start_time: 300, speaker: 'Renata', text: 'Pilha tecnologica: FlowConnect pra automacao, DataNest pra gestao, e Google Docs pra criacao.' },
      { segment_id: 'SEG-010-c', source_id: 'SRC-010', start_time: 700, speaker: 'Renata', text: 'A IA generativa entra na primeira versao do texto. Humano revisa e ajusta. Isso da 3x mais produtividade.' },
      { segment_id: 'SEG-010-d', source_id: 'SRC-010', start_time: 1200, speaker: 'Renata', text: 'Margem da agencia e 25 por cento. Nao e alta porque conteudo e mao de obra intensiva.' },
      { segment_id: 'SEG-011-a', source_id: 'SRC-011', start_time: 0, speaker: 'autor', text: 'Ferramentas de trafego pago: AdScope continua sendo a maior plataforma pra afiliados no Brasil.' },
      { segment_id: 'SEG-011-b', source_id: 'SRC-011', start_time: 0, speaker: 'autor', text: 'SearchBoost tem melhor intencao de compra mas e mais caro. SocialPulse ta crescendo rapido.' },
      { segment_id: 'SEG-011-c', source_id: 'SRC-011', start_time: 0, speaker: 'autor', text: 'Testei Native Ads (NativeReach/ContentWave) pra infoproduto. Funciona pra Scalability mas nao pra produto novo.' },
      { segment_id: 'SEG-011-d', source_id: 'SRC-011', start_time: 0, speaker: 'autor', text: 'Recomendacao: comeca com AdScope, testa com R$ 50/dia, escala o que der ROI positivo.' },
      { segment_id: 'SEG-013-a', source_id: 'SRC-013', start_time: 20, speaker: 'Roberto', text: 'Em 8 meses fui de zero a 200 mil reais por mes com infoprodutos. E 100 por cento replicavel.' },
      { segment_id: 'SEG-013-b', source_id: 'SRC-013', start_time: 200, speaker: 'Roberto', text: 'Meu segredo? Sistema de 3 funis rodando ao mesmo tempo. Cada funil com um produto diferente.' },
      { segment_id: 'SEG-013-c', source_id: 'SRC-013', start_time: 500, speaker: 'Roberto', text: 'Gasto 30 mil reais por mes em trafego pra manter isso. ROI de 5x.' },
      { segment_id: 'SEG-013-d', source_id: 'SRC-013', start_time: 800, speaker: 'Roberto', text: 'Mas isso funciona pra qualquer pessoa. So seguir o metodo.' },
      { segment_id: 'SEG-013-e', source_id: 'SRC-013', start_time: 1100, speaker: 'Roberto', text: 'Vou te ensinar tudo no meu curso, o link ta aqui na descricao' },
      { segment_id: 'SEG-014-a', source_id: 'SRC-014', start_time: 0, speaker: 'autor', text: 'CRM essencial pra afiliado: CampaignPro pra automacao de email, e PipelineCRM pra pipeline.' },
      { segment_id: 'SEG-014-b', source_id: 'SRC-014', start_time: 0, speaker: 'autor', text: 'Muitos afiliados ignoram CRM. Depois reclamam que nao conseguem escalar.' },
      { segment_id: 'SEG-014-c', source_id: 'SRC-014', start_time: 0, speaker: 'autor', text: 'Com CRM voce sabe exatamente qual lead entrou, qual link clicou, qual comprou.' },
      { segment_id: 'SEG-015-a', source_id: 'SRC-015', start_time: 10, speaker: 'Camila', text: 'TikTok em 2026 e sobre entretenimento primeiro, venda depois. Quem vende direto perde alcance.' },
      { segment_id: 'SEG-015-b', source_id: 'SRC-015', start_time: 200, speaker: 'Camila', text: 'Conteudo educativo funciona bem. Tutoriais, dicas rapidas, comparacoes.' },
      { segment_id: 'SEG-015-c', source_id: 'SRC-015', start_time: 500, speaker: 'Camila', text: 'Posto 4 vezes por dia. 3 organicos, 1 impulsionado.' },
      { segment_id: 'SEG-015-d', source_id: 'SRC-015', start_time: 800, speaker: 'Camila', text: 'Ferramentas: DesignNest pra thumbnail, ClipForge pra edicao, TikTok Analytics pra metricas.' },
      { segment_id: 'SEG-015-e', source_id: 'SRC-015', start_time: 1200, speaker: 'Thiago', text: 'E o TikTok Shop? Ja testou?' },
      { segment_id: 'SEG-015-f', source_id: 'SRC-015', start_time: 1220, speaker: 'Camila', text: 'Ainda nao. To esperando ver casos reais no Brasil antes de investir.' },
      { segment_id: 'SEG-016-a', source_id: 'SRC-016', start_time: 0, speaker: 'autor', text: 'Analytics de funil: MetricBase 4 basico, HeatView pra comportamento, e DataDash pra dados internos.' },
      { segment_id: 'SEG-016-b', source_id: 'SRC-016', start_time: 0, speaker: 'autor', text: 'Faltam ferramentas boas e faceis pra funil completo. O que existe ou e caro ou complicado demais.' },
      { segment_id: 'SEG-016-c', source_id: 'SRC-016', start_time: 0, speaker: 'autor', text: 'Uma ferramenta simples que mostrasse funil com origem, conversao e valor por etapa seria um bom produto.' },
      { segment_id: 'SEG-016-d', source_id: 'SRC-016', start_time: 0, speaker: 'autor', text: 'O mercado brasileiro tem espaco pra uma ferramenta de analytics focada em afiliados.' }
    ];
  }
  /* ========= TOOLS ========= */
  function buildTools() {
    return [
      { name: 'VideoSprint', category: 'edicao_video', frequency: 4, notes: 'Mencionado para gerar shorts automaticamente', sources: ['SRC-001', 'SRC-004'] },
      { name: 'ClipForge', category: 'edicao_video', frequency: 5, notes: 'Editor mobile favorito para edicao rapida', sources: ['SRC-001', 'SRC-009', 'SRC-015'] },
      { name: 'RenderWave', category: 'edicao_video', frequency: 2, notes: 'Render final profissional', sources: ['SRC-001', 'SRC-003'] },
      { name: 'EditPro', category: 'edicao_video', frequency: 1, notes: 'Editor desktop tradicional', sources: ['SRC-001'] },
      { name: 'FFmpeg', category: 'automacao_video', frequency: 2, notes: 'Automacao de batch de video', sources: ['SRC-003', 'SRC-006'] },
      { name: 'ReviewLoop', category: 'review', frequency: 1, notes: 'Review colaborativo de video', sources: ['SRC-003'] },
      { name: 'checkout', category: 'checkout', frequency: 5, notes: 'Maior plataforma de checkout/afiliados', sources: ['SRC-001', 'SRC-002', 'SRC-004', 'SRC-008'] },
      { name: 'ChatFlow', category: 'automacao', frequency: 1, notes: 'Sequenciamento no Mensagens', sources: ['SRC-002'] },
      { name: 'DesignNest', category: 'design', frequency: 3, notes: 'Design de thumbnails e artes', sources: ['SRC-004', 'SRC-009', 'SRC-015'] },
      { name: 'GenText', category: 'ia', frequency: 3, notes: 'Apoio criativo e revisao', sources: ['SRC-004', 'SRC-006'] },
      { name: 'VoiceForge', category: 'ia_audio', frequency: 1, notes: 'Narracao por IA', sources: ['SRC-006'] },
      { name: 'MotionCraft', category: 'edicao_video', frequency: 1, notes: 'Templates com datasource JSON', sources: ['SRC-006'] },
      { name: 'TaskHub', category: 'gestao', frequency: 2, notes: 'Gestao de equipe e projetos', sources: ['SRC-007', 'SRC-010'] },
      { name: 'TeamChat', category: 'comunicacao', frequency: 1, notes: 'Comunicacao de equipe', sources: ['SRC-007'] },
      { name: 'FileVault', category: 'armazenamento', frequency: 1, notes: 'Armazenamento de arquivos', sources: ['SRC-007'] },
      { name: 'ConvertNow', category: 'checkout', frequency: 2, notes: 'Melhor taxa de conversao entre checkouts', sources: ['SRC-008'] },
      { name: 'FlexCheckout', category: 'checkout', frequency: 2, notes: 'Plataforma mais flexivel', sources: ['SRC-008'] },
      { name: 'SellEngine', category: 'checkout', frequency: 1, notes: 'Antiga plataforma, ainda usada', sources: ['SRC-008'] },
      { name: 'LowFeePay', category: 'checkout', frequency: 1, notes: 'Taxa de 5.9 por cento, a mais barata', sources: ['SRC-008'] },
      { name: 'FlowConnect', category: 'automacao', frequency: 1, notes: 'Ex-FlowConnect, automacao de processos', sources: ['SRC-010'] },
      { name: 'DataNest', category: 'gestao', frequency: 1, notes: 'Base de dados flexivel', sources: ['SRC-010'] },
      { name: 'AdScope', category: 'trafego', frequency: 3, notes: 'Maior plataforma de anuncios', sources: ['SRC-011', 'SRC-002'] },
      { name: 'SearchBoost', category: 'trafego', frequency: 1, notes: 'Intencao de compra alta, custo maior', sources: ['SRC-011'] },
      { name: 'SocialPulse', category: 'trafego', frequency: 1, notes: 'Crescendo rapido', sources: ['SRC-011'] },
      { name: 'NativeReach', category: 'trafego', frequency: 1, notes: 'Native Ads para escala', sources: ['SRC-011'] },
      { name: 'CampaignPro', category: 'crm', frequency: 1, notes: 'Automacao de email marketing', sources: ['SRC-014'] },
      { name: 'PipelineCRM', category: 'crm', frequency: 1, notes: 'Pipeline de vendas', sources: ['SRC-014'] },
      { name: 'MetricBase', category: 'analytics', frequency: 1, notes: 'Analitico basico', sources: ['SRC-016'] },
      { name: 'HeatView', category: 'analytics', frequency: 1, notes: 'Comportamento do usuario', sources: ['SRC-016'] },
      { name: 'DataDash', category: 'analytics', frequency: 1, notes: 'Dashboard interno', sources: ['SRC-016'] },
      { name: 'FormCraft', category: 'captura', frequency: 1, notes: 'Captura de leads', sources: ['SRC-004'] },
      { name: 'MailCraft', category: 'email', frequency: 1, notes: 'Email marketing', sources: ['SRC-004'] }
    ];
  }
  /* ========= STRATEGIES ========= */
  function buildStrategies() {
    return [
      { name: 'Funi Unico Produto Um Canal', structure: 'organico TikTok -> lead magnet Telegram -> venda CheckoutFlow', roi_claimed: '3x-4x', risk: 'medio', scale: 'limitada', sources: ['SRC-001'] },
      { name: 'Coproducao Multi-parceiro', structure: 'divisao de tarefas por parceiro, lucro proporcional', roi_claimed: 'variavel', risk: 'baixo', scale: 'alta', sources: ['SRC-001', 'SRC-007'] },
      { name: 'Lancamento 7 Dias', structure: 'pre-lancamento -> abertura -> escassez -> fechamento', roi_claimed: '3.3x', risk: 'medio', scale: 'media', sources: ['SRC-002'] },
      { name: 'Pipeline IA de Video em Escala', structure: 'SmartModel script -> VoiceForge narracao -> FFmpeg render', roi_claimed: 'custo R$ 0,50/video', risk: 'medio', scale: 'alta', sources: ['SRC-006'] },
      { name: 'Trafego Pago + Conteudo Organico', structure: 'AdScope (lead) + organicos TikTok/Reels (alcance)', roi_claimed: 'ROI 3x-5x', risk: 'alto', scale: 'alta', sources: ['SRC-002', 'SRC-011', 'SRC-013'] },
      { name: 'Multi-funil Simultaneo', structure: '3 funis independentes rodando ao mesmo tempo', roi_claimed: 'ROI 5x', risk: 'alto', scale: 'alta', sources: ['SRC-013'] },
      { name: 'Template de Video Reutilizavel', structure: 'template unico -> variacoes ilimitadas', roi_claimed: '15 videos/hora', risk: 'baixo', scale: 'alta', sources: ['SRC-009'] },
      { name: 'Coproducao Conteudo Multi-canal', structure: 'conteudo base -> adaptacao por canal', roi_claimed: '10k/mes em 4 meses', risk: 'baixo', scale: 'alta', sources: ['SRC-007'] },
      { name: 'Agencia de Conteudo com IA', structure: 'IA gera rascunho -> humano revisa -> entrega', roi_claimed: 'margem 25%', risk: 'medio', scale: 'alta', sources: ['SRC-010'] },
      { name: 'Funil Completo com CRM', structure: 'captura -> CRM -> sequencia de emails -> venda', roi_claimed: '3.2% conversao', risk: 'baixo', scale: 'media', sources: ['SRC-002', 'SRC-014'] },
      { name: 'Social Commerce TikTok Shop', structure: 'video showcase -> compra in-app', roi_claimed: 'US$ 20B nos EUA', risk: 'alto', scale: 'potencialmente alta', sources: ['SRC-005', 'SRC-015'] },
      { name: 'Distribuicao Intensiva 20/dia', structure: '20 pecas/dia -> 2-3 bombam', roi_claimed: '10-15% virais', risk: 'medio', scale: 'alta', sources: ['SRC-004'] },
      { name: 'Native Ads para Infoproduto', structure: 'NativeReach -> pagina de vendas -> checkout', roi_claimed: 'funciona para escala', risk: 'alto', scale: 'alta', sources: ['SRC-011'] },
      { name: '3 Funis Rodando ao Mesmo Tempo', structure: 'produto A, B, C cada um com seu funil independente', roi_claimed: 'R$ 200k/mes', risk: 'alto', scale: 'alta', sources: ['SRC-013'] },
      { name: 'Conteudo Educativo TikTok', structure: 'tutorial/dica -> autoridade -> venda natural', roi_claimed: '4 posts/dia', risk: 'baixo', scale: 'media', sources: ['SRC-015'] },
      { name: 'CRM-Driven Funnel', structure: 'captura > qualificacao > nutricao > venda > pos-venda', roi_claimed: 'escalavel', risk: 'baixo', scale: 'alta', sources: ['SRC-014'] },
      { name: 'Ferramenta de Analytics para Afiliados', structure: 'fonte -> funil -> conversao por etapa -> valor', roi_claimed: 'oportunidade de mercado', risk: 'baixo', scale: 'alta', sources: ['SRC-016'] },
      { name: 'Revisao Humana + IA Generativa', structure: 'IA gera > humano revisa > 3x produtividade', roi_claimed: '3x produtividade', risk: 'baixo', scale: 'alta', sources: ['SRC-010'] }
    ];
  }
  /* ========= CLAIMS ========= */
  function buildClaims() {
    return [
      { text: 'R$ 0 a R$ 80k/mes em 6 meses', speaker: 'Carlos', source_id: 'SRC-001', type: 'revenue', context: 'Crescimento de receita mensal' },
      { text: 'Gastava uns 2 mil por mes de trafego', speaker: 'Carlos', source_id: 'SRC-001', type: 'cost', context: 'Investimento em trafego pago' },
      { text: 'Custo de aquisicao por lead era uns R$ 3,50', speaker: 'Carlos', source_id: 'SRC-001', type: 'metric', context: 'CAC' },
      { text: 'Margem liquida girava em torno de 35 a 40 por cento', speaker: 'Carlos', source_id: 'SRC-001', type: 'margin', context: 'Margem liquida do negocio' },
      { text: 'Perdeu uns 6 mil reais num produto que nao vingou', speaker: 'Carlos', source_id: 'SRC-001', type: 'loss', context: 'Prejuizo com produto' },
      { text: 'Faturamento bruto foi 40 mil reais. Custo total uns 12 mil. Lucro liquido 28 mil.', speaker: 'Ana', source_id: 'SRC-002', type: 'revenue', context: 'Lancamento de 7 dias' },
      { text: 'Gastei uns 8 mil em anuncios', speaker: 'Ana', source_id: 'SRC-002', type: 'cost', context: 'Investimento em trafego no lancamento' },
      { text: 'Teve 120 vendas no total. Ticket medio de R$ 333.', speaker: 'Ana', source_id: 'SRC-002', type: 'metric', context: 'Vendas do lancamento' },
      { text: 'A taxa de conversao de lead pra venda foi 3.2 por cento', speaker: 'Ana', source_id: 'SRC-002', type: 'metric', context: 'Conversao lead-venda' },
      { text: 'Geramos 200 videos por mes com uma equipe de 3 editores', speaker: 'Rafael', source_id: 'SRC-003', type: 'metric', context: 'Produtividade de edicao' },
      { text: 'taxa media de comissao e 50 por cento em infoprodutos', speaker: 'Lucas', source_id: 'SRC-004', type: 'metric', context: 'Comissao de afiliado' },
      { text: 'faturar R$ 30k num mes so de comissao', speaker: 'Lucas', source_id: 'SRC-004', type: 'revenue', context: 'Pico de comissao' },
      { text: 'pago 60 por cento de comissao pros melhores afiliados', speaker: 'Marina', source_id: 'SRC-004', type: 'metric', context: 'Comissao para afiliados' },
      { text: 'afiliados geram 70 por cento das minhas vendas', speaker: 'Marina', source_id: 'SRC-004', type: 'metric', context: 'Dependencia de afiliados' },
      { text: 'Invisto cerca de R$ 5 mil por mes em trafego pago. ROI medio de 3x.', speaker: 'Lucas', source_id: 'SRC-004', type: 'metric', context: 'ROI de trafego' },
      { text: 'TikTok Shop ja fez 20 bilhoes em vendas nos EUA', speaker: 'Juliana', source_id: 'SRC-005', type: 'market_data', context: 'Dado de mercado TikTok Shop' },
      { text: 'custo por video caiu pra R$ 0,50', speaker: 'Tiago', source_id: 'SRC-006', type: 'cost', context: 'Custo por video com pipeline IA' },
      { text: 'Em 4 meses tava ganhando 10 mil', speaker: 'Cristina', source_id: 'SRC-007', type: 'revenue', context: 'Resultado de coproducao' },
      { text: 'minha taxa de conversao de lead pra venda e 4.5 por cento', speaker: 'Marcelo', source_id: 'SRC-007', type: 'metric', context: 'Conversao pessoal' },
      { text: 'CheckoutFlow cobra 9.9 por cento mais taxa fixa', speaker: 'Daniela', source_id: 'SRC-008', type: 'cost', context: 'Taxa CheckoutFlow' },
      { text: 'LowFeePay cobra 5.9 por cento por venda', speaker: 'Daniela', source_id: 'SRC-008', type: 'cost', context: 'Taxa LowFeePay' },
      { text: 'Faco 15 videos por hora com template', speaker: 'Felipe', source_id: 'SRC-009', type: 'metric', context: 'Produtividade com template' },
      { text: 'Margem da agencia e 25 por cento', speaker: 'Renata', source_id: 'SRC-010', type: 'margin', context: 'Margem de agencia' },
      { text: 'R$ 200k/mes com infoproduto', speaker: 'Roberto', source_id: 'SRC-013', type: 'revenue', context: 'Receita mensal' },
      { text: 'Gasto 30 mil reais por mes em trafego', speaker: 'Roberto', source_id: 'SRC-013', type: 'cost', context: 'Investimento mensal' },
      { text: 'ROI de 5x', speaker: 'Roberto', source_id: 'SRC-013', type: 'metric', context: 'Retorno sobre investimento' }
    ];
  }
  /* ========= KNOWLEDGE CANDIDATES ========= */
  function buildKnowledgeCandidates() {
    return [
      { title: 'Template de video reduz tempo de edicao em 15x', summary: 'Criar um template padrao de video e reutilizar com variacoes permite produzir 15 videos por hora vs 1 video por hora sem template.', hypothesis: 'Um sistema de templates com variaveis de texto/imagem pode reduzir o tempo de edicao de video em pelo menos 10x.', sources: ['SRC-009', 'SRC-001'], departments: ['video'], experimentable: true },
      { title: 'Coproducao distribui risco e escala producao', summary: 'Multiplos parceiros dividindo tarefas (video, design, trafego) com lucro proporcional e mais sustentavel que operacao solo.', hypothesis: 'Um modelo de coproducao com 3-5 parceiros pode produzir 3x mais conteudo que um produtor solo com mesmo custo.', sources: ['SRC-007', 'SRC-001'], departments: ['video', 'affiliate_deals'], experimentable: true },
      { title: 'ROI de trafego pago para afiliados gira entre 3x e 5x', summary: 'Multiplos entrevistados reportam ROI de 3x a 5x em trafego pago para infoprodutos. Variacao depende do produto e funil.', hypothesis: 'Campanhas de AdScope para infoprodutos com ticket medio R$ 200+ geram ROI minimo de 3x.', sources: ['SRC-004', 'SRC-013'], departments: ['affiliate_deals'], experimentable: true },
      { title: 'IA generativa + revisao humana da 3x mais produtividade', summary: 'Usar IA para primeira versao e humano para revisao final triplica a producao de conteudo sem perder qualidade.', hypothesis: 'Um workflow de IA + revisor humano pode produzir 3x mais conteudo que producao 100% humana com qualidade similar.', sources: ['SRC-010', 'SRC-006'], departments: ['script', 'video'], experimentable: true },
      { title: 'Checkout CheckoutFlow domina mercado mas tem taxas altas', summary: 'CheckoutFlow tem maior base de afiliados (vantagem para lancamentos) mas cobra 9.9% + taxa fixa. ConvertNow tem melhor conversao.', hypothesis: 'Para produtos de ticket baixo (< R$ 100), ConvertNow ou LowFeePay geram margem liquida maior que CheckoutFlow.', sources: ['SRC-008', 'SRC-002'], departments: ['affiliate_deals'], experimentable: true },
      { title: 'Ferramentas de analytics para afiliados sao carentes no Brasil', summary: 'Multiplos criadores mencionam falta de ferramentas simples que mostrem funil completo com origem, conversao e valor por etapa.', hypothesis: 'Uma ferramenta SaaS de analytics focada em afiliados brasileiros teria demanda e baixa concorrencia.', sources: ['SRC-016', 'SRC-014'], departments: ['strategy_intelligence'], experimentable: false },
      { title: 'TikTok Shop Brasil tem potencial mas falta maturidade', summary: 'TikTok Shop nos EUA fez US$ 20B em vendas. No Brasil ainda engatinha. Produtos visuais funcionam melhor.', hypothesis: 'Produtos com forte apelo visual (moda, casa, beleza) tem 2x mais conversao que produtos tecnicos no TikTok Shop.', sources: ['SRC-005', 'SRC-015'], departments: ['strategy_intelligence', 'affiliate_deals'], experimentable: true },
      { title: 'Distribuicao e o gargalo, nao producao', summary: 'Multiplos criadores concordam que producao de conteudo nao e mais o problema. Distribuir e conseguir alcance e o desafio real.', hypothesis: 'Para cada 10 pecas de conteudo produzidas, apenas 1-2 recebem alcance organico significativo.', sources: ['SRC-004', 'SRC-001', 'SRC-007'], departments: ['affiliate_deals', 'strategy_intelligence'], experimentable: true },
      { title: 'CRM e negligenciado por afiliados', summary: 'Poucos afiliados usam CRM. Com CRM e possivel rastrear lead, cliques e compras, permitindo escala.', hypothesis: 'Afiliados que usam CRM tem 2x mais taxa de conversao que afiliados que nao usam.', sources: ['SRC-014', 'SRC-002'], departments: ['affiliate_deals'], experimentable: false },
      { title: 'Multi-funil simultaneo e estrate g ia de alto risco e alto retorno', summary: 'Rodar 3 funis ao mesmo tempo requer R$ 30k/mes em trafego mas promete R$ 200k/mes de receita.', hypothesis: 'Rodar 2+ funis simultaneos reduz risco de variacao de performance comparado a 1 funil apenas.', sources: ['SRC-013'], departments: ['affiliate_deals'], experimentable: true },
      { title: 'VideoSprint e ferramenta chave para escala de shorts', summary: 'Multiplos entrevistados usam VideoSprint para gerar shorts automaticamente a partir de videos longos.', hypothesis: 'Ferramentas de clipping automatico geram 5x mais shorts no mesmo tempo que edicao manual.', sources: ['SRC-001', 'SRC-004'], departments: ['video'], experimentable: true },
      { title: 'Conteudo educativo gera mais engajamento que conteudo de venda', summary: 'Estrategia de entretenimento/educacao primeiro, venda depois, gera mais alcance e autoridade.', hypothesis: 'Proporcao 80% educativo / 20% vendas gera 3x mais seguidores que proporcao inversa.', sources: ['SRC-015'], departments: ['script', 'affiliate_deals'], experimentable: true }
    ];
  }
  /* ========= CARDS PROMOTED ========= */
  function buildCards() {
    return [
      { card_id: 'KC-001', title: 'Template de video reduz tempo de edicao em 15x', summary: 'Sistema de templates com variacoes de texto/imagem reduz drasticamente o tempo de edicao.', hypothesis: 'Um sistema de templates com variaveis reduz tempo de edicao em 10x.', sources: ['SRC-009', 'SRC-001'], confidence: 0.75, applicability: 'alta', departments: ['video'], risks: ['Requer investimento inicial de criacao de templates', 'Depende de ferramenta de template compativel'], cost_estimate: 'R$ 500-2000 para criar templates iniciais', status: 'promoted', approved_by: 'Leandro', approved_at: '2026-07-14T10:00:00Z', experiment_id: 'EXP-001' },
      { card_id: 'KC-002', title: 'Coproducao distribui risco e escala producao', summary: 'Modelo com multiplos parceiros dividindo tarefas e mais sustentavel que operacao solo.', hypothesis: 'Coproducao com 3-5 parceiros produz 3x mais conteudo com mesmo custo.', sources: ['SRC-007', 'SRC-001'], confidence: 0.7, applicability: 'alta', departments: ['video', 'affiliate_deals'], risks: ['Requis coordenacao entre parceiros', 'Divisao de lucro proporcional pode gerar conflito'], cost_estimate: 'Tempo de coordenacao, sem custo direto', status: 'promoted', approved_by: 'Leandro', approved_at: '2026-07-14T11:00:00Z', experiment_id: 'EXP-002' },
      { card_id: 'KC-003', title: 'IA + revisao humana da 3x produtividade', summary: 'IA gera primeira versao, humano revisa. Triplica producao de conteudo.', hypothesis: 'IA + revisor humano produz 3x mais com qualidade similar.', sources: ['SRC-010', 'SRC-006'], confidence: 0.65, applicability: 'media', departments: ['script', 'video'], risks: ['Qualidade da IA pode ser inconsistente', 'Revisor pode se tornar gargalo'], cost_estimate: 'Custo de API de IA', status: 'promoted', approved_by: 'Leandro', approved_at: '2026-07-14T14:00:00Z', experiment_id: 'EXP-003' },
      { card_id: 'KC-004', title: 'TikTok Shop Brasil: potencial mas prematuro', summary: 'TikTok Shop promete mas ainda nao ha dados conclusivos no Brasil.', hypothesis: 'Produtos visuais convertem 2x mais no TikTok Shop.', sources: ['SRC-005', 'SRC-015'], confidence: 0.35, applicability: 'baixa', departments: ['strategy_intelligence', 'affiliate_deals'], risks: ['Plataforma ainda imatura no Brasil', 'Sem dados locais de conversao'], cost_estimate: 'Nao recomendado agora', status: 'promoted', approved_by: 'Leandro', approved_at: '2026-07-15T08:00:00Z', experiment_id: null },
      { card_id: 'KC-005', title: 'Distribuicao e gargalo principal do conteudo', summary: 'Produzir e facil. Distribuir e conseguir alcance e o verdadeiro desafio.', hypothesis: 'Apenas 10-20% do conteudo recebe alcance organico significativo.', sources: ['SRC-004', 'SRC-001', 'SRC-007'], confidence: 0.8, applicability: 'alta', departments: ['affiliate_deals', 'strategy_intelligence'], risks: [], cost_estimate: '', status: 'promoted', approved_by: 'Leandro', approved_at: '2026-07-15T10:00:00Z', experiment_id: 'EXP-004' },
      { card_id: 'KC-006', title: 'ROI de trafego pago para afiliados: 3x-5x', summary: 'Multiplos entrevistados reportam ROI de 3x a 5x em trafego pago.', hypothesis: 'AdScope para infoprodutos com ticket R$ 200+ gera ROI minimo de 3x.', sources: ['SRC-004', 'SRC-013'], confidence: 0.5, applicability: 'media', departments: ['affiliate_deals'], risks: ['ROI depende de produto/funil', 'Custo de trafego varia com concorrencia'], cost_estimate: 'R$ 2000-5000 para teste', status: 'promoted', approved_by: 'Leandro', approved_at: '2026-07-15T14:00:00Z', experiment_id: 'EXP-005' },
      { card_id: 'KC-007', title: 'Templates no MotionCraft com datasource JSON', summary: 'Usar MotionCraft com datasource JSON permite gerar centenas de variacoes de video.', hypothesis: 'AE com datasource JSON gera 100 variacoes no tempo de 1 edicao manual.', sources: ['SRC-006'], confidence: 0.5, applicability: 'media', departments: ['video'], risks: ['AE requer licenca paga', 'Curva de aprendizado'], cost_estimate: 'R$ 150/mes (MotionCraft)', status: 'promoted', approved_by: 'System', approved_at: '2026-07-15T16:00:00Z', experiment_id: null },
      { card_id: 'KC-008', title: 'Checkout CheckoutFlow vs alternativas: margem importa', summary: 'CheckoutFlow domina afiliados mas taxas altas. Para produtos de ticket baixo, alternativas sao melhores.', hypothesis: 'LowFeePay/ConvertNow geram margem maior que CheckoutFlow para tickets < R$ 100.', sources: ['SRC-008', 'SRC-002', 'SRC-004'], confidence: 0.6, applicability: 'alta', departments: ['affiliate_deals'], risks: ['CheckoutFlow tem maior base de afiliados', 'Alternativas tem menos integracoes'], cost_estimate: 'Zero para testar (cadastro gratuito)', status: 'promoted', approved_by: 'Leandro', approved_at: '2026-07-16T09:00:00Z', experiment_id: null }
    ];
  }
  /* ========= EXPERIMENTS ========= */
  function buildExperiments() {
    return [
      { experiment_id: 'EXP-001', knowledge_card_id: 'KC-001', hypothesis: 'Um sistema de templates com variaveis de texto/imagem reduz o tempo de edicao de video em pelo menos 10x.', baseline: 'Edicao manual: 1 video/hora', variant: 'Template com variaveis: 10+ videos/hora', steps: ['Criar 3 templates base no ClipForge/DaVinci', 'Criar planilha de variacoes (texto, cor, musica)', 'Medir tempo de 10 edicoes com template vs 10 manuais'], max_cost: 500, duration_days: 21, primary_metric: 'videos por hora', secondary_metrics: ['qualidade subjetiva (1-5)', 'custo por video'], success_condition: 'Template produz 5x mais videos/hora que manual', stop_condition: 'Template produz menos que manual OU qualidade < 3', risk: 'baixo', providers_needed: [], channel: 'TikTok/Reels', status: 'active', approved: true, published: false, result: null, conclusion: '' },
      { experiment_id: 'EXP-002', knowledge_card_id: 'KC-002', hypothesis: 'Modelo de coproducao com 3-5 parceiros produz 3x mais conteudo com mesmo custo que operacao solo.', baseline: 'Operacao solo: 5 videos/semana', variant: '3 parceiros em coproducao: 15+ videos/semana', steps: ['Selecionar 3 parceiros (video, design, trafego)', 'Definir divisao de lucro (ex: 40/30/30)', 'Rodar por 30 dias', 'Comparar producao com mes anterior solo'], max_cost: 0, duration_days: 60, primary_metric: 'videos produzidos por semana', secondary_metrics: ['custo por video', 'qualidade media', 'satisfacao dos parceiros'], success_condition: '3x mais videos com qualidade similar', stop_condition: 'Qualidade cai abaixo do aceitavel OU parceiro desiste', risk: 'medio', providers_needed: [], channel: 'YouTube/TikTok', status: 'proposed', approved: false, published: false, result: null, conclusion: '' },
      { experiment_id: 'EXP-003', knowledge_card_id: 'KC-003', hypothesis: 'Workflow IA + revisor humano produz 3x mais scripts que producao 100% humana com qualidade similar.', baseline: 'Script 100% humano: 4 scripts/dia', variant: 'IA + revisor: 12 scripts/dia', steps: ['Configurar pipeline SmartModel -> estrutura de script', 'Revisor humano ajusta e aprova', 'Comparar 20 scripts de cada metodo em qualidade cega'], max_cost: 200, duration_days: 30, primary_metric: 'scripts por dia', secondary_metrics: ['qualidade cega (1-10)', 'custo por script'], success_condition: '3x scripts/dia com qualidade > 7/10', stop_condition: 'Qualidade media abaixo de 5/10', risk: 'baixo', providers_needed: ['openai'], channel: 'todos', status: 'proposed', approved: false, published: false, result: null, conclusion: '' },
      { experiment_id: 'EXP-004', knowledge_card_id: 'KC-005', hypothesis: 'Apenas 10-20% do conteudo produzido recebe alcance organico significativo.', baseline: 'Produzir e publicar sem estrategia de distribuicao', variant: 'Produzir + estrategia de distribuicao multicanal', steps: ['Durante 2 semanas: produzir 20 pecas sem estrategia de distribuicao', 'Medir alcance de cada peca', 'Proxima 2 semanas: 20 pecas com estrategia (cross-post, hashtags, horarios)', 'Comparar alcance medio'], max_cost: 0, duration_days: 30, primary_metric: 'alcance medio por peca', secondary_metrics: ['engajamento medio', 'taxa de conversao'], success_condition: 'Estrategia de distribuicao dobra alcance medio', stop_condition: 'Diferenca < 20%', risk: 'baixo', providers_needed: [], channel: 'TikTok/Instagram/YouTube', status: 'proposed', approved: false, published: false, result: null, conclusion: '' },
      { experiment_id: 'EXP-005', knowledge_card_id: 'KC-006', hypothesis: 'AdScope para infoprodutos com ticket medio R$ 200+ gera ROI minimo de 3x.', baseline: 'Sem trafego pago', variant: 'R$ 2000/mes em AdScope', steps: ['Criar campanha AdScope com R$ 50/dia', 'Produto: infoproduto com ticket R$ 200+', 'Rodar por 30 dias', 'Calcular ROI'], max_cost: 2000, duration_days: 30, primary_metric: 'ROI (receita / gasto)', secondary_metrics: ['CAC', 'taxa de conversao', 'impressoes'], success_condition: 'ROI >= 3x', stop_condition: 'ROI < 1x no dia 15', risk: 'alto', providers_needed: ['meta_ads'], channel: 'AdScope', status: 'proposed', approved: false, published: false, result: null, conclusion: '' },
      { experiment_id: 'EXP-006', knowledge_card_id: 'KC-004', hypothesis: 'Produtos visuais tem 2x mais conversao no TikTok Shop que produtos tecnicos.', baseline: '', variant: '', steps: ['Aguardar maturidade do TikTok Shop no Brasil', 'Selecionar 2 produtos visuais + 2 tecnicos', 'Produzir 5 videos para cada'], max_cost: 1000, duration_days: 90, primary_metric: 'taxa de conversao', secondary_metrics: ['visualizacoes', 'cliques no link'], success_condition: 'Produtos visuais convertem 2x mais', stop_condition: 'TikTok Shop nao disponivel ou muda termos', risk: 'alto', providers_needed: [], channel: 'TikTok Shop', status: 'paused', approved: false, published: false, result: null, conclusion: 'Aguardando maturidade da plataforma no Brasil' },
      { experiment_id: 'EXP-007', knowledge_card_id: null, hypothesis: 'Conteudo educativo gera 3x mais seguidores que conteudo de venda direta.', baseline: '80% venda / 20% educativo', variant: '20% venda / 80% educativo', steps: ['Criar 2 contas no TikTok', 'Conta A: 80% venda, 20% educativo', 'Conta B: 20% venda, 80% educativo', 'Comparar crescimento em 30 dias'], max_cost: 0, duration_days: 30, primary_metric: 'crescimento de seguidores', secondary_metrics: ['engajamento', 'alcance por post'], success_condition: 'Conta B cresce 3x mais', stop_condition: 'Diferenca < 50%', risk: 'baixo', providers_needed: [], channel: 'social_short', status: 'proposed', approved: false, published: false, result: null, conclusion: '' },
      { experiment_id: 'EXP-008', knowledge_card_id: null, hypothesis: 'Funil com sequencia de 5 emails converte 2x mais que venda direta.', baseline: 'Venda direta sem sequencia de emails', variant: 'Funil com 5 emails automatizados', steps: ['Configurar sequencia de 5 emails (D1, D3, D5, D7, D10)', 'Segmentar 200 leads para cada grupo', 'Comparar conversao em 15 dias'], max_cost: 300, duration_days: 15, primary_metric: 'taxa de conversao', secondary_metrics: ['taxa de abertura', 'taxa de clique'], success_condition: 'Funil de emails converte 2x mais', stop_condition: 'Menos de 50 leads por grupo', risk: 'baixo', providers_needed: ['email'], channel: 'Email', status: 'proposed', approved: false, published: false, result: null, conclusion: '' }
    ];
  }
  /* ========= PATTERNS ========= */
  function buildPatterns() {
    return [
      { tag: 'edicao_video', description: 'Ferramentas e tecnicas de edicao de video', strength: 85, sources: ['SRC-001', 'SRC-003', 'SRC-006', 'SRC-009', 'SRC-015'] },
      { tag: 'trafego', description: 'Estrategias e custos de trafego pago', strength: 72, sources: ['SRC-001', 'SRC-002', 'SRC-004', 'SRC-011', 'SRC-013'] },
      { tag: 'funil', description: 'Estrutura e otimizacao de funil de vendas', strength: 78, sources: ['SRC-001', 'SRC-002', 'SRC-004', 'SRC-012', 'SRC-013', 'SRC-016'] },
      { tag: 'coproducao', description: 'Modelo de producao colaborativa entre parceiros', strength: 65, sources: ['SRC-001', 'SRC-007'] },
      { tag: 'checkout', description: 'Plataformas de checkout e comparacao de taxas', strength: 60, sources: ['SRC-002', 'SRC-004', 'SRC-008'] },
      { tag: 'automacao', description: 'Automacao de processos de producao de conteudo', strength: 55, sources: ['SRC-006', 'SRC-010', 'SRC-014'] },
      { tag: 'ia', description: 'Uso de inteligencia artificial na producao', strength: 58, sources: ['SRC-004', 'SRC-006', 'SRC-010'] },
      { tag: 'afiliados', description: 'Estrategias e metricas do mercado de afiliados', strength: 82, sources: ['SRC-001', 'SRC-002', 'SRC-004', 'SRC-008', 'SRC-011', 'SRC-013', 'SRC-014'] },
      { tag: 'tiktok_shop', description: 'TikTok Shop como canal de vendas', strength: 35, sources: ['SRC-005', 'SRC-015'] },
      { tag: 'analytics', description: 'Ferramentas e metricas de analise', strength: 45, sources: ['SRC-016', 'SRC-014'] },
      { tag: 'crm', description: 'Gestao de leads e relacionamento', strength: 42, sources: ['SRC-014', 'SRC-002'] },
      { tag: 'social_commerce', description: 'Vendas diretas em redes sociais', strength: 30, sources: ['SRC-005', 'SRC-015'] },
      { tag: 'conteudo', description: 'Producao e distribuicao de conteudo', strength: 75, sources: ['SRC-001', 'SRC-004', 'SRC-007', 'SRC-010', 'SRC-015'] },
      { tag: 'marketing_digital', description: 'Estrategias gerais de marketing digital', strength: 70, sources: ['SRC-001', 'SRC-002', 'SRC-004', 'SRC-011', 'SRC-013'] }
    ];
  }
  /* ========= SOFTWARE OPPS ========= */
  function buildSoftwareOpps() {
    return [
      { title: 'Ferramenta de analytics para funil de afiliados', description: 'Dashboard que mostra funil completo com origem, conversao, valor por etapa, focado em afiliados brasileiros.', frequency: 5, intensity: 8, source_count: 4, payment_willingness: 'alta', alternatives_exist: 'poucas', complexity: 'media', risk: 'baixo', synergy_with_factory: true, sources: ['SRC-016', 'SRC-014'] },
      { title: 'Gerador automatico de shorts com template', description: 'Ferramenta que recebe video longo e gera N variacoes de short com template, texto e cortes automaticos.', frequency: 6, intensity: 9, source_count: 5, payment_willingness: 'media', alternatives_exist: 'sim', complexity: 'alta', risk: 'medio', synergy_with_factory: true, sources: ['SRC-001', 'SRC-003', 'SRC-006', 'SRC-009'] },
      { title: 'Plataforma de coproducao com gestao integrada', description: 'Plataforma que conecta parceiros de coproducao, gerencia tarefas, divisao de lucro e comunicacao.', frequency: 4, intensity: 7, source_count: 3, payment_willingness: 'media', alternatives_exist: 'sim', complexity: 'alta', risk: 'alto', synergy_with_factory: false, sources: ['SRC-007', 'SRC-001'] },
      { title: 'CRM simplificado para afiliados', description: 'CRM leve e barato focado em afiliados, com rastreamento de lead, link e comissao.', frequency: 7, intensity: 9, source_count: 5, payment_willingness: 'alta', alternatives_exist: 'sim', complexity: 'media', risk: 'medio', synergy_with_factory: true, sources: ['SRC-014', 'SRC-002', 'SRC-004'] },
      { title: 'Motor de recomendacao de checkout', description: 'Ferramenta que recomenda a melhor plataforma de checkout baseada no produto, ticket e publico.', frequency: 3, intensity: 6, source_count: 3, payment_willingness: 'baixa', alternatives_exist: 'poucas', complexity: 'baixa', risk: 'baixo', synergy_with_factory: true, sources: ['SRC-008', 'SRC-002'] },
      { title: 'Suite de templates para video vendas', description: 'Biblioteca de templates de video prontos para vender produtos, com variaveis editaveis.', frequency: 8, intensity: 9, source_count: 6, payment_willingness: 'alta', alternatives_exist: 'sim', complexity: 'media', risk: 'baixo', synergy_with_factory: true, sources: ['SRC-009', 'SRC-001', 'SRC-003', 'SRC-006'] }
    ];
  }
  /* ========= REVENUE CLAIMS (detected) ========= */
  function buildRevenueClaims() {
    return [
      { claim_id: 'RC-001', source_id: 'SRC-001', speaker: 'Carlos', claimed_value: '80000', currency: 'BRL', period: 'mensal', context: 'R$ 0 a R$ 80k/mes em 6 meses', classification: 'partial' },
      { claim_id: 'RC-002', source_id: 'SRC-001', speaker: 'Carlos', claimed_value: '60000', currency: 'BRL', period: 'mensal', context: '60 mil reais por mes em 3 meses', classification: 'partial' },
      { claim_id: 'RC-003', source_id: 'SRC-002', speaker: 'Ana', claimed_value: '40000', currency: 'BRL', period: 'lancamento', context: 'Faturamento bruto 40k em 7 dias', classification: 'partial' },
      { claim_id: 'RC-004', source_id: 'SRC-004', speaker: 'Lucas', claimed_value: '30000', currency: 'BRL', period: 'mensal', context: '30k num mes de comissao', classification: 'partial' },
      { claim_id: 'RC-005', source_id: 'SRC-005', speaker: 'Juliana', claimed_value: '20000000000', currency: 'USD', period: 'total', context: 'TikTok Shop 20 bilhoes nos EUA', classification: 'accepted' },
      { claim_id: 'RC-006', source_id: 'SRC-007', speaker: 'Cristina', claimed_value: '10000', currency: 'BRL', period: 'mensal', context: '10 mil em 4 meses', classification: 'partial' },
      { claim_id: 'RC-007', source_id: 'SRC-013', speaker: 'Roberto', claimed_value: '200000', currency: 'BRL', period: 'mensal', context: '200k/mes com infoprodutos', classification: 'promotional' },
      { claim_id: 'RC-008', source_id: 'SRC-002', speaker: 'Ana', claimed_value: '28000', currency: 'BRL', period: 'lancamento', context: 'Lucro liquido 28k', classification: 'partial' }
    ];
  }
  /* ========= LEARNING LOG ========= */
  function buildLearningLog() {
    return [
      { id: 'LL-001', source_id: 'SRC-001', title: 'CAC em funil de conteudo', observation: 'CAC de R$ 3,50 com otimizacao vs R$ 8,00 inicial. Reducao de 56%.', cardinality: 'mitigado', applied: false, approved: false },
      { id: 'LL-002', source_id: 'SRC-002', title: 'Dependencia de afiliados', observation: '1/3 das vendas vieram de afiliados. Proporcao relevante mas nao dominante.', cardinality: 'observado', applied: false, approved: false },
      { id: 'LL-003', source_id: 'SRC-004', title: 'Taxa de viralizacao 10-15%', observation: '2-3 pecas bombam a cada 20 publicadas. ~10-15% de taxa de viralizacao.', cardinality: 'estimado', applied: false, approved: false },
      { id: 'LL-004', source_id: 'SRC-007', title: 'Tempo medio de aprendizado coproducao', observation: '4 meses para atingir R$ 10k/mes em coproducao partindo do zero.', cardinality: 'relatado', applied: false, approved: false },
      { id: 'LL-005', source_id: 'SRC-009', title: 'Produtividade com templates', observation: '15 videos/hora com template vs 1 video/hora sem template. Ganho de 15x.', cardinality: 'comprovado', applied: false, approved: true },
      { id: 'LL-006', source_id: 'SRC-001', title: 'Perda em produto que nao vingou', observation: 'Prejuizo de R$ 6k em produto que nao vingou. Risco real de novos produtos.', cardinality: 'relatado', applied: false, approved: false },
      { id: 'LL-007', source_id: 'SRC-016', title: 'Falta de ferramentas de analytics', observation: 'Ausencia de ferramentas simples de funil para afiliados brasileiros.', cardinality: 'observado', applied: false, approved: true },
      { id: 'LL-008', source_id: 'SRC-010', title: 'Margem de agencia de conteudo', observation: 'Margem de 25% em agencia de conteudo. Conteudo e mao de obra intensiva.', cardinality: 'relatado', applied: false, approved: false }
    ];
  }
  return {
    buildSources: buildSources,
    buildSegments: buildSegments,
    buildTools: buildTools,
    buildStrategies: buildStrategies,
    buildClaims: buildClaims,
    buildKnowledgeCandidates: buildKnowledgeCandidates,
    buildCards: buildCards,
    buildExperiments: buildExperiments,
    buildPatterns: buildPatterns,
    buildSoftwareOpps: buildSoftwareOpps,
    buildRevenueClaims: buildRevenueClaims,
    buildLearningLog: buildLearningLog
  };
})();
