/* Offer Intelligence — Dados MOCK v1.0 */
/* Todas as ofertas sao ficticias. Nenhum dado e real. */

const OFFERS = [
  {
    id: "off-001",
    product_name: "CreatorFlow Academy",
    domain: "creatorflow.academy",
    platform: "Hotmart",
    platform_logo: "HM",
    niche: "educacao",
    country: "BR",
    currency: "BRL",
    current_price: 297.00,
    old_price: 597.00,
    commission_percent: 50,
    cookie_days: 30,
    affiliate_available: true,
    affiliate_program: "Hotmart Afiliados",
    search_volume: 8400,
    growth_30d: 23,
    growth_90d: 67,
    trend_direction: "up",
    trend_persistence: "sustained_6m",
    active_ads: 12,
    advertiser_count: 4,
    marketplace_trust: 0.78,
    reviews_avg: 4.6,
    review_count: 342,
    seller_reputation: "alta",
    competition_level: "medio",
    saturation_level: "medio",
    risk_flags: [],
    status: "growing",
    evidence_source: "url_intake+manual",
    evidence_freshness_days: 3,
    evidence_confidence: 0.85,
    last_updated: "2026-07-15",
    shipping_notes: "digital",
    has_physical: false,
    policy_risk: "baixo",
    description: "Plataforma completa para criadores de conteudo digital com modulos de producao, publicacao e metricas.",
    image_url: "",
    official_product_url: "",
    sales_page_url: "",
    affiliate_program_url: "",
    checkout_url: "",
    ad_library_url: "",
    evidence_url: "",
    verified_at: "",
    verification_status: "unverified"
  },
  {
    id: "off-002",
    product_name: "FitHome Method",
    domain: "fithome.com.br",
    platform: "Braip",
    platform_logo: "BP",
    niche: "saude",
    country: "BR",
    currency: "BRL",
    current_price: 147.00,
    old_price: 197.00,
    commission_percent: 40,
    cookie_days: 30,
    affiliate_available: true,
    affiliate_program: "Braip Afiliados",
    search_volume: 15200,
    growth_30d: 8,
    growth_90d: 15,
    trend_direction: "up",
    trend_persistence: "sustained_3m",
    active_ads: 23,
    advertiser_count: 8,
    marketplace_trust: 0.76,
    reviews_avg: 4.3,
    review_count: 187,
    seller_reputation: "alta",
    competition_level: "alto",
    saturation_level: "alto",
    risk_flags: ["saude_sem_comprovacao"],
    status: "growing",
    evidence_source: "url_intake+manual",
    evidence_freshness_days: 7,
    evidence_confidence: 0.72,
    last_updated: "2026-07-14",
    shipping_notes: "digital",
    has_physical: false,
    policy_risk: "alto",
    description: "Metodo de exercicios em casa com 12 semanas de treino, dieta e acompanhamento.",
    image_url: ""
  },
  {
    id: "off-003",
    product_name: "SmartDesk Pro",
    domain: "smartdeskpro.com",
    platform: "Amazon",
    platform_logo: "AZ",
    niche: "escritorio",
    country: "BR",
    currency: "BRL",
    current_price: 899.00,
    old_price: 1299.00,
    commission_percent: 6,
    cookie_days: 1,
    affiliate_available: true,
    affiliate_program: "Amazon Associates",
    search_volume: 3200,
    growth_30d: -5,
    growth_90d: 12,
    trend_direction: "stable",
    trend_persistence: "stable_12m",
    active_ads: 5,
    advertiser_count: 3,
    marketplace_trust: 0.92,
    reviews_avg: 4.5,
    review_count: 890,
    seller_reputation: "alta",
    competition_level: "medio",
    saturation_level: "medio",
    risk_flags: [],
    status: "stable",
    evidence_source: "url_intake+amazon_api",
    evidence_freshness_days: 1,
    evidence_confidence: 0.92,
    last_updated: "2026-07-16",
    shipping_notes: "frete_gratis",
    has_physical: true,
    policy_risk: "baixo",
    description: "Mesa elevavel eletrica com regulagem de altura, tampo de 120x60cm, memoria de posicoes.",
    image_url: ""
  },
  {
    id: "off-004",
    product_name: "LanguageSprint",
    domain: "languagesprint.io",
    platform: "Hotmart",
    platform_logo: "HM",
    niche: "educacao",
    country: "BR",
    currency: "BRL",
    current_price: 97.00,
    old_price: 197.00,
    commission_percent: 60,
    cookie_days: 30,
    affiliate_available: true,
    affiliate_program: "Hotmart Afiliados",
    search_volume: 22100,
    growth_30d: 45,
    growth_90d: 120,
    trend_direction: "up",
    trend_persistence: "sustained_12m",
    active_ads: 31,
    advertiser_count: 12,
    marketplace_trust: 0.74,
    reviews_avg: 4.2,
    review_count: 560,
    seller_reputation: "media",
    competition_level: "alto",
    saturation_level: "medio",
    risk_flags: [],
    status: "growing",
    evidence_source: "url_intake+manual",
    evidence_freshness_days: 2,
    evidence_confidence: 0.78,
    last_updated: "2026-07-15",
    shipping_notes: "digital",
    has_physical: false,
    policy_risk: "baixo",
    description: "Metodo intensivo de aprendizado de idiomas com IA, 15 minutos por dia.",
    image_url: ""
  },
  {
    id: "off-005",
    product_name: "CommercePilot",
    domain: "commercepilot.io",
    platform: "Digistore24",
    platform_logo: "D24",
    niche: "ferramentas",
    country: "US",
    currency: "USD",
    current_price: 49.00,
    old_price: 99.00,
    commission_percent: 40,
    cookie_days: 60,
    affiliate_available: true,
    affiliate_program: "Digistore24 Afiliados",
    search_volume: 5800,
    growth_30d: 15,
    growth_90d: 42,
    trend_direction: "up",
    trend_persistence: "sustained_6m",
    active_ads: 8,
    advertiser_count: 2,
    marketplace_trust: 0.74,
    reviews_avg: 4.1,
    review_count: 124,
    seller_reputation: "media",
    competition_level: "baixo",
    saturation_level: "baixo",
    risk_flags: [],
    status: "growing",
    evidence_source: "manual+affiliate_network",
    evidence_freshness_days: 5,
    evidence_confidence: 0.7,
    last_updated: "2026-07-14",
    shipping_notes: "digital",
    has_physical: false,
    policy_risk: "baixo",
    description: "Suite de ferramentas para automacao de e-commerce com integracoes multi-plataforma.",
    image_url: ""
  },
  {
    id: "off-006",
    product_name: "FocusWave",
    domain: "focuswave.app",
    platform: "ClickBank",
    platform_logo: "CB",
    niche: "produtividade",
    country: "US",
    currency: "USD",
    current_price: 27.00,
    old_price: 47.00,
    commission_percent: 75,
    cookie_days: 60,
    affiliate_available: true,
    affiliate_program: "ClickBank",
    search_volume: 1900,
    growth_30d: -12,
    growth_90d: -8,
    trend_direction: "down",
    trend_persistence: "declining_3m",
    active_ads: 2,
    advertiser_count: 1,
    marketplace_trust: 0.62,
    reviews_avg: 3.8,
    review_count: 45,
    seller_reputation: "baixa",
    competition_level: "medio",
    saturation_level: "baixo",
    risk_flags: ["baixa_reputacao"],
    status: "declining",
    evidence_source: "manual",
    evidence_freshness_days: 15,
    evidence_confidence: 0.55,
    last_updated: "2026-07-10",
    shipping_notes: "digital",
    has_physical: false,
    policy_risk: "baixo",
    description: "App de foco e produtividade com tecnica Pomodoro, tracker de tarefas e musicas ambiente.",
    image_url: ""
  },
  {
    id: "off-007",
    product_name: "AudioCraft Studio",
    domain: "audiocraft.studio",
    platform: "Hotmart",
    platform_logo: "HM",
    niche: "musica",
    country: "BR",
    currency: "BRL",
    current_price: 197.00,
    old_price: null,
    commission_percent: 30,
    cookie_days: 30,
    affiliate_available: true,
    affiliate_program: "Hotmart Afiliados",
    search_volume: 1200,
    growth_30d: 35,
    growth_90d: 89,
    trend_direction: "up",
    trend_persistence: "emerging_3m",
    active_ads: 0,
    advertiser_count: 0,
    marketplace_trust: 0.7,
    reviews_avg: 4.4,
    review_count: 78,
    seller_reputation: "media",
    competition_level: "baixo",
    saturation_level: "baixo",
    risk_flags: ["sem_anuncios"],
    status: "growing",
    evidence_source: "manual",
    evidence_freshness_days: 4,
    evidence_confidence: 0.62,
    last_updated: "2026-07-15",
    shipping_notes: "digital",
    has_physical: false,
    policy_risk: "baixo",
    description: "Curso completo de producao musical com DAW, gravacao, mixagem e masterizacao.",
    image_url: ""
  },
  {
    id: "off-008",
    product_name: "KitchenEdge",
    domain: "kitchenedge.com.br",
    platform: "Mercado Livre",
    platform_logo: "ML",
    niche: "casa",
    country: "BR",
    currency: "BRL",
    current_price: 159.90,
    old_price: 199.90,
    commission_percent: 4,
    cookie_days: 1,
    affiliate_available: false,
    affiliate_program: "",
    search_volume: 4500,
    growth_30d: 3,
    growth_90d: 5,
    trend_direction: "stable",
    trend_persistence: "stable_6m",
    active_ads: 0,
    advertiser_count: 0,
    marketplace_trust: 0.86,
    reviews_avg: 4.2,
    review_count: 230,
    seller_reputation: "alta",
    competition_level: "alto",
    saturation_level: "medio",
    risk_flags: ["sem_afiliacao"],
    status: "stable",
    evidence_source: "url_intake+ml_api",
    evidence_freshness_days: 2,
    evidence_confidence: 0.88,
    last_updated: "2026-07-16",
    shipping_notes: "frete_gratis",
    has_physical: true,
    policy_risk: "baixo",
    description: "Faqueiro profissional em aco inox com 24 pecas, cabos ergonomicos e laminas temperadas.",
    image_url: ""
  },
  {
    id: "off-009",
    product_name: "TravelMind",
    domain: "travelmind.co",
    platform: "ClickBank",
    platform_logo: "CB",
    niche: "turismo",
    country: "US",
    currency: "USD",
    current_price: 37.00,
    old_price: 67.00,
    commission_percent: 60,
    cookie_days: 60,
    affiliate_available: true,
    affiliate_program: "ClickBank",
    search_volume: 680,
    growth_30d: -25,
    growth_90d: -45,
    trend_direction: "down",
    trend_persistence: "declining_6m",
    active_ads: 1,
    advertiser_count: 1,
    marketplace_trust: 0.58,
    reviews_avg: 3.5,
    review_count: 23,
    seller_reputation: "baixa",
    competition_level: "baixo",
    saturation_level: "baixo",
    risk_flags: ["declinio_acelerado", "baixa_reputacao"],
    status: "declining",
    evidence_source: "manual",
    evidence_freshness_days: 20,
    evidence_confidence: 0.45,
    last_updated: "2026-07-08",
    shipping_notes: "digital",
    has_physical: false,
    policy_risk: "medio",
    description: "Guia de viagens inteligente com roteiros personalizados por IA e descontos exclusivos.",
    image_url: ""
  },
  {
    id: "off-010",
    product_name: "DevLaunch",
    domain: "devlaunch.io",
    platform: "Digistore24",
    platform_logo: "D24",
    niche: "tecnologia",
    country: "US",
    currency: "USD",
    current_price: 197.00,
    old_price: 497.00,
    commission_percent: 50,
    cookie_days: 60,
    affiliate_available: true,
    affiliate_program: "Digistore24 Afiliados",
    search_volume: 3400,
    growth_30d: 55,
    growth_90d: 180,
    trend_direction: "up",
    trend_persistence: "sustained_12m",
    active_ads: 18,
    advertiser_count: 7,
    marketplace_trust: 0.82,
    reviews_avg: 4.7,
    review_count: 420,
    seller_reputation: "alta",
    competition_level: "medio",
    saturation_level: "baixo",
    risk_flags: [],
    status: "growing",
    evidence_source: "url_intake+manual",
    evidence_freshness_days: 1,
    evidence_confidence: 0.88,
    last_updated: "2026-07-16",
    shipping_notes: "digital",
    has_physical: false,
    policy_risk: "baixo",
    description: "Bootcamp completo de desenvolvimento full-stack com mentorias ao vivo e projetos reais.",
    image_url: ""
  },
  {
    id: "off-011",
    product_name: "GreenHome Guide",
    domain: "greenhomeguide.eco",
    platform: "Hotmart",
    platform_logo: "HM",
    niche: "sustentabilidade",
    country: "BR",
    currency: "BRL",
    current_price: 67.00,
    old_price: 127.00,
    commission_percent: 50,
    cookie_days: 30,
    affiliate_available: true,
    affiliate_program: "Hotmart Afiliados",
    search_volume: 920,
    growth_30d: 5,
    growth_90d: 8,
    trend_direction: "stable",
    trend_persistence: "stable_3m",
    active_ads: 0,
    advertiser_count: 0,
    marketplace_trust: 0.68,
    reviews_avg: 4.0,
    review_count: 34,
    seller_reputation: "media",
    competition_level: "baixo",
    saturation_level: "baixo",
    risk_flags: ["sem_anuncios", "dados_insuficientes"],
    status: "insufficient_data",
    evidence_source: "manual",
    evidence_freshness_days: 10,
    evidence_confidence: 0.48,
    last_updated: "2026-07-12",
    shipping_notes: "digital",
    has_physical: false,
    policy_risk: "baixo",
    description: "Guia pratico para transformar sua casa em um ambiente sustentavel com economia de recursos.",
    image_url: ""
  },
  {
    id: "off-012",
    product_name: "MarketPulse Tools",
    domain: "marketpulse.tools",
    platform: "Braip",
    platform_logo: "BP",
    niche: "ferramentas",
    country: "BR",
    currency: "BRL",
    current_price: 197.00,
    old_price: 297.00,
    commission_percent: 35,
    cookie_days: 30,
    affiliate_available: true,
    affiliate_program: "Braip Afiliados",
    search_volume: 2100,
    growth_30d: 18,
    growth_90d: 45,
    trend_direction: "up",
    trend_persistence: "sustained_6m",
    active_ads: 6,
    advertiser_count: 3,
    marketplace_trust: 0.76,
    reviews_avg: 4.3,
    review_count: 156,
    seller_reputation: "alta",
    competition_level: "medio",
    saturation_level: "medio",
    risk_flags: [],
    status: "growing",
    evidence_source: "url_intake+manual",
    evidence_freshness_days: 3,
    evidence_confidence: 0.78,
    last_updated: "2026-07-15",
    shipping_notes: "digital",
    has_physical: false,
    policy_risk: "baixo",
    description: "Suite de ferramentas de pesquisa de mercado com analise de concorrentes e tendencias.",
    image_url: ""
  },
  {
    id: "off-013",
    product_name: "FoneMax Pro",
    domain: "fonemax.com.br",
    platform: "Amazon",
    platform_logo: "AZ",
    niche: "tecnologia",
    country: "BR",
    currency: "BRL",
    current_price: 249.90,
    old_price: 349.90,
    commission_percent: 5,
    cookie_days: 1,
    affiliate_available: true,
    affiliate_program: "Amazon Associates",
    search_volume: 18900,
    growth_30d: -3,
    growth_90d: 22,
    trend_direction: "stable",
    trend_persistence: "stable_12m",
    active_ads: 15,
    advertiser_count: 9,
    marketplace_trust: 0.92,
    reviews_avg: 4.4,
    review_count: 2340,
    seller_reputation: "alta",
    competition_level: "alto",
    saturation_level: "alto",
    risk_flags: [],
    status: "stable",
    evidence_source: "url_intake+amazon_api",
    evidence_freshness_days: 1,
    evidence_confidence: 0.95,
    last_updated: "2026-07-16",
    shipping_notes: "frete_gratis",
    has_physical: true,
    policy_risk: "baixo",
    description: "Fone Bluetooth com cancelamento de ruido ativo, 40h de bateria e carregamento rapido.",
    image_url: ""
  },
  {
    id: "off-014",
    product_name: "CursoReceitaFit",
    domain: "cursoreceitafit.com.br",
    platform: "Hotmart",
    platform_logo: "HM",
    niche: "saude",
    country: "BR",
    currency: "BRL",
    current_price: 47.00,
    old_price: null,
    commission_percent: 70,
    cookie_days: 30,
    affiliate_available: true,
    affiliate_program: "Hotmart Afiliados",
    search_volume: 7800,
    growth_30d: 42,
    growth_90d: 95,
    trend_direction: "up",
    trend_persistence: "sustained_6m",
    active_ads: 14,
    advertiser_count: 5,
    marketplace_trust: 0.72,
    reviews_avg: 4.1,
    review_count: 210,
    seller_reputation: "media",
    competition_level: "alto",
    saturation_level: "alto",
    risk_flags: ["saude_sem_comprovacao"],
    status: "growing",
    evidence_source: "url_intake+manual",
    evidence_freshness_days: 2,
    evidence_confidence: 0.72,
    last_updated: "2026-07-16",
    shipping_notes: "digital",
    has_physical: false,
    policy_risk: "alto",
    description: "Livro digital com 200 receitas fit, low carb e high protein para emagrecimento saudavel.",
    image_url: ""
  },
  {
    id: "off-015",
    product_name: "SecurePass Manager",
    domain: "securepass.app",
    platform: "ClickBank",
    platform_logo: "CB",
    niche: "tecnologia",
    country: "US",
    currency: "USD",
    current_price: 19.00,
    old_price: 39.00,
    commission_percent: 60,
    cookie_days: 60,
    affiliate_available: true,
    affiliate_program: "ClickBank",
    search_volume: 450,
    growth_30d: 2,
    growth_90d: 5,
    trend_direction: "stable",
    trend_persistence: "stable_12m",
    active_ads: 0,
    advertiser_count: 0,
    marketplace_trust: 0.6,
    reviews_avg: 3.9,
    review_count: 18,
    seller_reputation: "baixa",
    competition_level: "baixo",
    saturation_level: "baixo",
    risk_flags: ["sem_anuncios", "dados_insuficientes"],
    status: "insufficient_data",
    evidence_source: "manual",
    evidence_freshness_days: 25,
    evidence_confidence: 0.38,
    last_updated: "2026-07-05",
    shipping_notes: "digital",
    has_physical: false,
    policy_risk: "baixo",
    description: "Gerenciador de senhas com criptografia ponta-a-ponta e autenticacao biometrica.",
    image_url: ""
  }
];

/* URLs MOCK — estrutura preparada para futura integracao com links reais */
/* Nenhum dominio real. Todos os campos vazios por enquanto. */
const MOCK_URL_FIELDS = {
  official_product_url: "",
  sales_page_url: "",
  affiliate_program_url: "",
  checkout_url: "",
  ad_library_url: "",
  evidence_url: "",
  verified_at: "",
  verification_status: "unverified"
};

/* Aviso para exibir quando links estiverem indisponiveis em modo MOCK */
const MOCK_URL_DISCLAIMER = "Indisponivel em dados MOCK. Quando houver uma fonte validada, este botao abrira a pagina oficial em uma nova aba.";

/* Alertas MOCK */
const MOCK_ALERTS = [
  { id: "alt-001", offer_id: "off-004", type: "crescimento", message: "LanguageSprint cresceu 45% em 30 dias", severity: "info", date: "2026-07-15" },
  { id: "alt-002", offer_id: "off-010", type: "crescimento", message: "DevLaunch atingiu 180% de crescimento em 90 dias", severity: "positive", date: "2026-07-15" },
  { id: "alt-003", offer_id: "off-006", type: "declinio", message: "FocusWave em declinio ha 3 meses consecutivos", severity: "warning", date: "2026-07-14" },
  { id: "alt-004", offer_id: "off-009", type: "declinio", message: "TravelMind apresenta declinio acelerado de -45%", severity: "critical", date: "2026-07-13" },
  { id: "alt-005", offer_id: "off-011", type: "dados", message: "GreenHome Guide possui dados insuficientes para score confiavel", severity: "warning", date: "2026-07-12" },
  { id: "alt-006", offer_id: "off-001", type: "tendencia", message: "CreatorFlow Academy mantem tendencia de alta sustentada por 6 meses", severity: "info", date: "2026-07-15" },
  { id: "alt-007", offer_id: "off-008", type: "oportunidade", message: "KitchenEdge sem link de afiliado disponivel - acao necessaria", severity: "info", date: "2026-07-16" }
];

/* Configuracoes padrao */
const DEFAULT_SETTINGS = {
  theme: "dark",
  density: "comfortable",
  rows_per_page: 15,
  currency: "BRL",
  default_country: "",
  min_confidence: 0,
  show_advanced: false
};

/* Nichos */
const NICHES = [
  "educacao", "saude", "escritorio", "ferramentas", "produtividade",
  "musica", "casa", "turismo", "tecnologia", "sustentabilidade"
];

/* Plataformas */
const PLATFORMS = [
  "Hotmart", "Braip", "Amazon", "Digistore24", "ClickBank", "Mercado Livre"
];

/* Historico de tendencia MOCK para graficos (90 dias) */
function generateTrendHistory(base, strength, direction) {
  const points = [];
  let val = base * (direction === "up" ? 0.6 : direction === "down" ? 1.4 : 0.9);
  for (let i = 90; i >= 0; i--) {
    const noise = (Math.random() - 0.5) * base * 0.15;
    const trend = direction === "up" ? base * 0.008 * strength : direction === "down" ? -base * 0.008 * strength : 0;
    val += trend + noise;
    val = Math.max(base * 0.3, val);
    points.push({ day: i, value: Math.round(val) });
  }
  return points;
}

/* Pre-historico para cada oferta */
const TREND_HISTORIES = {};
OFFERS.forEach(o => {
  TREND_HISTORIES[o.id] = generateTrendHistory(o.search_volume, o.growth_90d / 100, o.trend_direction);
});
