"""Tool Runtime & Capability Registry for AI Company.

All tools (YouTube, GitHub, ElevenLabs, Figma, etc.) follow the
same contract. Employee never accesses tools directly — always
via ToolRuntime -> Tool Adapter -> External Tool.

The ToolRegistry decouples employee intent (capability) from
tool selection. Employees request capabilities, not tool names.
"""

from __future__ import annotations

from .adapters import (
    AbstractToolAdapter,
    AdapterConfigStatus,
    AdapterExecutionResult,
    AdapterStatus,
    CredentialRequirement,
    ElevenLabsAdapter,
    ExecutionMode,
    FFmpegRenderAdapter,
    GitHubAdapter,
    OwnerGuidance,
    PlaywrightAdapter,
    ToolRequest,
    ToolResponse,
    YouTubeAdapter,
)
from .capabilities import Capability
from .http import (
    AuthExpiredError,
    HttpClient,
    HttpAuthenticationFailed,
    HttpError,
    HttpMethod,
    HttpQuotaExceeded,
    HttpRateLimited,
    HttpRequest,
    HttpRequestCompleted,
    HttpRequestFailed,
    HttpRequestStarted,
    HttpResponse,
    HttpRetry,
    MockHttpClient,
    NetworkUnavailableError,
    QuotaExceededError,
    RateLimitConfig,
    RateLimitError,
    RateLimiter,
    RealHttpClient,
    RetryExhaustedError,
    RetryPolicy,
    TimeoutError,
    TimeoutPolicy,
)
from .models import ToolDefinition, ToolStatus
from .provider_control import (
    ProviderBudget,
    ProviderBudgetDecision,
    ProviderBudgetGuard,
    ProviderPricing,
    ProviderUsageRecord,
    ProviderUsageSummary,
)
from .provider_panel import ProviderPanelRenderer
from .provider_settings import (
    ProviderControlCenter,
    ProviderControlProfile,
    ProviderControlSnapshot,
    ProviderSecretSlot,
)
from .providers import (
    ElevenLabsProvider,
    GitHubProvider,
    GoogleProvider,
    OpenAIProvider,
    PlaywrightProvider,
    Provider,
)
from .secrets import (
    MockSecretProvider,
    SecretKey,
    SecretProvider,
    SecretValue,
)
from .registry import (
    CapabilityRegistered,
    CapabilityRequested,
    CapabilityResolved,
    CapabilityUnavailable,
    ToolRegistry,
    ToolSelected,
)
from .runtime import (
    ToolConfigured,
    ToolError,
    ToolExecuted,
    ToolReady,
    ToolRegistered,
    ToolReleased,
    ToolRequested,
    ToolRuntime,
    ToolUnavailable,
    ToolValidated,
)

__all__ = [
    "AbstractToolAdapter",
    "AdapterConfigStatus",
    "AdapterExecutionResult",
    "AdapterStatus",
    "AuthExpiredError",
    "Capability",
    "CapabilityRegistered",
    "CapabilityRequested",
    "CapabilityResolved",
    "CapabilityUnavailable",
    "CredentialRequirement",
    "ElevenLabsAdapter",
    "ElevenLabsProvider",
    "ExecutionMode",
    "FFmpegRenderAdapter",
    "GitHubAdapter",
    "GitHubProvider",
    "GoogleProvider",
    "HttpAuthenticationFailed",
    "HttpClient",
    "HttpError",
    "HttpMethod",
    "HttpQuotaExceeded",
    "HttpRateLimited",
    "HttpRequest",
    "HttpRequestCompleted",
    "HttpRequestFailed",
    "HttpRequestStarted",
    "HttpResponse",
    "HttpRetry",
    "MockHttpClient",
    "MockSecretProvider",
    "NetworkUnavailableError",
    "OpenAIProvider",
    "OwnerGuidance",
    "PlaywrightAdapter",
    "PlaywrightProvider",
    "Provider",
    "ProviderBudget",
    "ProviderBudgetDecision",
    "ProviderBudgetGuard",
    "ProviderControlCenter",
    "ProviderControlProfile",
    "ProviderControlSnapshot",
    "ProviderPanelRenderer",
    "ProviderPricing",
    "ProviderSecretSlot",
    "ProviderUsageRecord",
    "ProviderUsageSummary",
    "QuotaExceededError",
    "RateLimitConfig",
    "RateLimitError",
    "RateLimiter",
    "RealHttpClient",
    "RetryExhaustedError",
    "RetryPolicy",
    "SecretKey",
    "SecretProvider",
    "SecretValue",
    "TimeoutError",
    "TimeoutPolicy",
    "ToolConfigured",
    "ToolDefinition",
    "ToolError",
    "ToolExecuted",
    "ToolReady",
    "ToolRegistry",
    "ToolReleased",
    "ToolRequest",
    "ToolRequested",
    "ToolResponse",
    "ToolRuntime",
    "ToolSelected",
    "ToolStatus",
    "ToolUnavailable",
    "ToolValidated",
    "YouTubeAdapter",
]
