"""Core events package for AI Content Factory."""

from .bus import EventBus, EventCallback, EventEnvelope
from .contracts import (
    BaseEventDispatcher,
    BaseEventRegistry,
    BaseEventSubscriber,
    BaseEventValidator,
    EventDispatcherContract,
    EventRegistryContract,
    EventSubscriberContract,
    EventValidatorContract,
)
from .dispatcher import EventDispatcher
from .domain_events import (
    CollaborationCompleted,
    CollaborationStarted,
    CompanyTaskCompleted,
    CompanyTaskReceived,
    CompanyTaskRouted,
    ConversationCreated,
    DecisionApproved,
    DecisionRejected,
    ExecutionCompleted,
    ExecutionFailed,
    ExecutionPersisted,
    ExecutionRestored,
    ExecutionStarted,
    KnowledgePromoted,
    MemoryDocumentArchived,
    MemoryDocumentCreated,
    MemoryDocumentUpdated,
    MemoryRecordCreated,
    MessageAdded,
    OrchestratorExecutionCompleted,
    OrchestratorExecutionStarted,
    ParticipantResponded,
    QualityValidationFinished,
    QualityValidationStarted,
    RecommendationCreated,
    SessionCreated,
    SessionLoaded,
    SessionSaved,
    SkillCreated,
    SkillLevelChanged,
    SkillPromoted,
    SnapshotCreated,
    SnapshotLoaded,
    WorkflowCompleted,
    WorkflowStarted,
    WorkflowTaskCompleted,
    WorkflowTaskStarted,
)
from .handlers import EventHandler
from .exceptions import (
    EventDispatchError,
    EventError,
    EventRegistryError,
    EventSubscriberError,
    EventValidationError,
)
from .models import (
    BaseEvent,
    EventContext,
    EventMetadata,
    EventPriority,
    EventResult,
    EventStatus,
    EventType,
)
from .registry import EventRegistry
from .subscribers import EventSubscriber
from .validators import EventValidator

__all__ = [
    "BaseEvent",
    "EventBus",
    "EventCallback",
    "EventEnvelope",
    "EventHandler",
    "BaseEventDispatcher",
    "BaseEventRegistry",
    "BaseEventSubscriber",
    "BaseEventValidator",
    "CollaborationCompleted",
    "CollaborationStarted",
    "CompanyTaskCompleted",
    "CompanyTaskReceived",
    "CompanyTaskRouted",
    "ConversationCreated",
    "DecisionApproved",
    "DecisionRejected",
    "EventContext",
    "EventDispatchError",
    "EventDispatcher",
    "EventDispatcherContract",
    "EventError",
    "EventMetadata",
    "EventPriority",
    "EventRegistry",
    "EventRegistryContract",
    "EventRegistryError",
    "EventResult",
    "EventStatus",
    "EventSubscriber",
    "EventSubscriberContract",
    "EventSubscriberError",
    "EventType",
    "EventValidationError",
    "EventValidator",
    "EventValidatorContract",
    "ExecutionCompleted",
    "ExecutionFailed",
    "ExecutionPersisted",
    "ExecutionRestored",
    "ExecutionStarted",
    "KnowledgePromoted",
    "MemoryDocumentArchived",
    "MemoryDocumentCreated",
    "MemoryDocumentUpdated",
    "MemoryRecordCreated",
    "MessageAdded",
    "OrchestratorExecutionCompleted",
    "OrchestratorExecutionStarted",
    "ParticipantResponded",
    "QualityValidationFinished",
    "QualityValidationStarted",
    "RecommendationCreated",
    "SessionCreated",
    "SessionLoaded",
    "SessionSaved",
    "SkillCreated",
    "SkillLevelChanged",
    "SkillPromoted",
    "SnapshotCreated",
    "SnapshotLoaded",
    "WorkflowCompleted",
    "WorkflowStarted",
    "WorkflowTaskCompleted",
    "WorkflowTaskStarted",
]
